#!/usr/bin/env python3
"""Build assets/data/signals.js from the eBPF sources in crates/kestrel-ebpf.

Emits `const SIGNALS = {...};` -- the load-as-a-script convention data.js,
campaigns.js and ebpf.js use, denormalised so the pages render without any
further joining: every map carries its declaration, its key and value shape,
and the programs that write it (producers) or read it (consumers) with the
call site that proves each edge.

THE SHAPE OF THE CRATE

  Three objects, each a unity build: src/host.c, src/net_sock.c and
  src/net_pkt.c include every shared source exactly once, so an object holds
  one copy of each map and every program in it shares them. A program is a
  SEC() entry function; 116 of them are listed in rust/contract.rs
  (CATALOGUE), one bit each in load_state.skipped.

WHAT IS PARSED

  * Each object's root, preprocessed the way clang sees it: #include lines
    followed in order (-I include -I src), #if/#ifdef/#else evaluated with
    the object's own KESTREL_OBJ_* define, KESTREL_TEST unset. The test
    fixtures (t_*, l0_selftest, l0_bench, t_own) therefore do not appear.
  * Every `SEC(".maps")` declaration left after that, per object. A map that
    survives in all three objects is one the loader creates once and shares
    by descriptor (docs/LOAD_CONTRACT.md section 1); one that survives in a
    single object belongs to that object.
  * Every SEC() program, written out or generated by a macro on a line of
    its own (L7_DECODER), with the comment above it.
  * Map-helper calls reached from a program through the object's static
    inline functions, its global (__noinline) functions, bpf_loop and
    bpf_timer callbacks and function-like macros. A WRITE is an update /
    delete / ringbuf output / timer init / storage get with F_CREATE, or a
    lookup whose result the same function writes through or returns as a
    writable pointer. Everything else that touches the map is a READ.

LIMITS, stated so the pages can state them

  * Reachability follows names: a callee passed as a value (a bpf_loop
    callback) is reached by its name appearing in the caller, which
    over-approximates slightly.
  * Userspace is not analysed. A map with in-kernel readers and no in-kernel
    writer is written by the loader or the daemon; one with writers and no
    readers is drained by userspace. Both are reported as such, and the load
    contract's own words about pinning and loader writes are carried in the
    family blurbs.

    python3 assets/data/source/signals_to_js.py \\
        ../crates/kestrel-ebpf assets/data/signals.js
"""
import datetime, json, os, re, sys

ROOT = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else "../crates/kestrel-ebpf")
OUT  = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else "assets/data/signals.js")
INC  = os.path.join(ROOT, "include")
SRC  = os.path.join(ROOT, "src")
SOURCE_LABEL = "crates/kestrel-ebpf"

rel  = lambda p: os.path.relpath(p, ROOT)
read = lambda p: open(p, encoding="utf-8", errors="replace").read()

# ------------------------------------------------------------------- sources
headers, sources = [], []
for base, _d, files in os.walk(INC):
    headers += [os.path.join(base, f) for f in files if f.endswith(".h")]
for base, _d, files in os.walk(SRC):
    sources += [os.path.join(base, f) for f in files if f.endswith(".c")]
headers.sort(); sources.sort()
ALL = headers + sources
TEXT = {p: read(p) for p in ALL}

def strip_comments(s):
    """Blank out comments, preserving every offset and newline."""
    out, i, n = list(s), 0, len(s)
    def blank(a, b):
        for k in range(a, b):
            if out[k] != "\n": out[k] = " "
    while i < n:
        if s.startswith("/*", i):
            j = s.find("*/", i + 2); j = n if j < 0 else j + 2
            blank(i, j); i = j
        elif s.startswith("//", i):
            j = s.find("\n", i); j = n if j < 0 else j
            blank(i, j); i = j
        elif s[i] in "\"'":
            q = s[i]; i += 1
            while i < n and s[i] != q:
                if s[i] == "\\": i += 1
                i += 1
            i += 1
        else:
            i += 1
    return "".join(out)

CODE = {p: strip_comments(t) for p, t in TEXT.items()}
lineno = lambda text, pos: text.count("\n", 0, pos) + 1

def clean_prose(body):
    lines = [re.sub(r"^\s*\*\s?", "", ln).strip() for ln in body.split("\n")]
    return re.sub(r"\s+", " ", " ".join(x for x in lines if x)).strip()

def doc_before(text, pos):
    """The comment block above `pos`, looking past #if/#define and blank lines."""
    head = text[:pos]
    skipped = 0
    while True:
        stripped = head.rstrip()
        if stripped.endswith("*/"):
            start = stripped.rfind("/*")
            if start < 0: return ""
            return clean_prose(stripped[start + 2: -2])
        nl = stripped.rfind("\n")
        line = stripped[nl + 1:].strip()
        if skipped >= 3 or (line and not re.match(r"#\s*(if|ifdef|ifndef|else|elif|endif|define)\b", line)):
            return ""
        skipped += 1
        head = stripped[:nl + 1]

# -------------------------------------------------------------- struct/enums
STRUCTS, ENUMS = {}, {}
FIELD_RE = re.compile(
    r"^(?P<type>(?:const |volatile |unsigned |signed |struct |union |enum )*"
    r"[A-Za-z_][A-Za-z_0-9]*\s*\**)\s*(?P<name>[A-Za-z_][A-Za-z_0-9]*)"
    r"(?P<arr>(?:\s*\[[^\]]*\])*)\s*(?::\s*(?P<bits>\d+))?$")
SKIP_TY = {"return", "if", "else", "static", "_Static_assert", "typedef"}

def comments_in(chunk):
    out = []
    for m in re.finditer(r"/\*(.*?)\*/|//([^\n]*)", chunk, re.S):
        out.append((m.start(), clean_prose(m.group(1) or m.group(2))))
    return out

def parse_struct_body(body):
    """Members of a struct, each with the comment the source keeps beside it.

    A comment on the same line as the PREVIOUS member's semicolon is that
    member's trailing note. A nested union or struct is flattened: its
    members are listed as the record's own, which is how the wire reads."""
    fields, bare, start = [], strip_comments(body), 0
    for m in re.finditer(r";", bare):
        raw, start = body[start:m.start()], m.end()
        if not raw.strip(): continue
        nl = raw.find("\n")
        notes, trailing = [], []
        for at, txt in comments_in(raw):
            (trailing if (nl >= 0 and at < nl) else notes).append(txt)
        if trailing and fields:
            fields[-1]["note"] = re.sub(r"\s+", " ",
                (fields[-1]["note"] + " " + " ".join(trailing)).strip())
        clean = re.sub(r"\s+", " ", strip_comments(raw)).strip()
        # a nested aggregate opens here: keep what follows its brace
        clean = re.sub(r"^(?:[^{}]*\{\s*)+", "", clean)
        clean = re.sub(r"^\}\s*\w*\s*", "", clean).strip()
        if not clean or "(" in clean: continue
        fm = FIELD_RE.match(clean)
        if not fm: continue
        ty = re.sub(r"\s+", " ", fm.group("type")).strip()
        if ty.split()[0] in SKIP_TY: continue
        fields.append({"type": ty,
                       "name": fm.group("name") + (fm.group("arr") or "").replace(" ", ""),
                       "bits": fm.group("bits"),
                       "note": re.sub(r"\s+", " ", " ".join(notes)).strip()})
    return fields

for p in ALL:
    t = TEXT[p]
    for m in re.finditer(r"\bstruct\s+([A-Za-z_][A-Za-z_0-9]*)\s*\{", t):
        name, i, depth = m.group(1), m.end() - 1, 0
        for j in range(i, len(t)):
            if t[j] == "{": depth += 1
            elif t[j] == "}":
                depth -= 1
                if depth == 0: break
        else: continue
        if 'SEC(".maps")' in t[j + 1: j + 40]: continue
        if name in STRUCTS: continue
        STRUCTS[name] = {"file": rel(p), "line": lineno(t, m.start()),
                         "doc": doc_before(t, m.start()),
                         "fields": parse_struct_body(t[i + 1: j])}
    for m in re.finditer(r"\benum\s+([A-Za-z_][A-Za-z_0-9]*)\s*\{([^}]*)\}", t, re.S):
        if m.group(1) in ENUMS: continue
        vals = []
        for item in m.group(2).split(","):
            note = " ".join(x.strip() for pair in
                            re.findall(r"/\*(.*?)\*/|//([^\n]*)", item, re.S)
                            for x in pair if x)
            c = re.sub(r"\s+", " ", strip_comments(item)).strip()
            mm = re.match(r"([A-Za-z_][A-Za-z_0-9]*)\s*(?:=\s*(.+))?$", c)
            if mm: vals.append({"name": mm.group(1), "value": (mm.group(2) or "").strip(),
                                "note": re.sub(r"\s+", " ", note).strip()})
        ENUMS[m.group(1)] = {"file": rel(p), "line": lineno(t, m.start()),
                             "doc": doc_before(t, m.start()), "values": vals}

# --------------------------------------------------------------- directives
def directives(text):
    out = []
    for m in re.finditer(r"^[ \t]*#[ \t]*(ifdef|ifndef|if|elif|else|endif|define|include)\b"
                         r"((?:[^\n\\]|\\\n|\\)*)", text, re.M):
        out.append((m.start(), m.end(), m.group(1),
                    re.sub(r"\s+", " ", m.group(2).replace("\\\n", " ")).strip()))
    return out
DIRS = {p: directives(CODE[p]) for p in ALL}

SAFE = re.compile(r"^[0-9()!&|<>=+\-*/% ]*$")
KNOWN_UNSET = ("KESTREL_", "__TARGET_ARCH_")

def _d(sym, defs):
    if sym in defs: return "1"
    if sym.startswith(KNOWN_UNSET): return "0"
    return sym            # undecidable -> leaves an identifier behind

def _eval(expr, defs):
    """Evaluate a #if expression. Returns True / False / None (undecidable)."""
    e = expr
    e = re.sub(r"defined\s*\(\s*([A-Za-z_]\w*)\s*\)", lambda m: _d(m.group(1), defs), e)
    e = re.sub(r"defined\s+([A-Za-z_]\w*)", lambda m: _d(m.group(1), defs), e)
    for _ in range(4):
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b", lambda m: defs.get(m.group(1), m.group(1)), e)
        if e2 == e: break
        e = e2
    e = e.replace("&&", " and ").replace("||", " or ").replace("!=", " __NE__ ")
    e = re.sub(r"!", " not ", e).replace("__NE__", "!=")
    if re.search(r"[A-Za-z_]", e.replace(" and ", " ").replace(" or ", " ").replace(" not ", " ")):
        return None
    try:
        return bool(eval(e, {"__builtins__": {}}, {}))
    except Exception:
        return None

BYREL = {}
for p in headers: BYREL[os.path.relpath(p, INC)] = p
for p in sources: BYREL[os.path.relpath(p, SRC)] = p

def resolve_include(name):
    return BYREL.get(name) or BYREL.get(os.path.basename(name))

def preprocess(path, defs, seen, units, order):
    """Walk one file as the preprocessor would: #include followed where it
    stands, regions a false #if excludes blanked, simple #defines recorded.
    Appends (path, filtered_text) to units; `order` is the include depth."""
    text = CODE[path]
    out = list(text)
    stack = []            # {state, done, start}
    def blank(a, b):
        for i in range(a, min(b, len(out))):
            if out[i] != "\n": out[i] = " "
    def active():
        return all(f["state"] is not False for f in stack)
    for at, end, kind, expr in DIRS[path]:
        if kind in ("ifdef", "ifndef", "if"):
            if not active():
                stack.append({"state": False, "done": True, "start": end}); continue
            if kind == "ifdef":    v = _eval("defined(%s)" % (expr.split() or [""])[0], defs)
            elif kind == "ifndef": v = _eval("!defined(%s)" % (expr.split() or [""])[0], defs)
            else:                  v = _eval(expr, defs)
            stack.append({"state": v, "done": v is True, "start": end})
            continue
        if kind in ("elif", "else", "endif"):
            if not stack: continue
            fr = stack[-1]
            outer = all(f["state"] is not False for f in stack[:-1])
            if fr["state"] is False and outer:
                blank(fr["start"], at)
            if kind == "elif":
                v = False if fr["done"] else _eval(expr, defs)
                fr["state"] = v; fr["done"] = fr["done"] or (v is True); fr["start"] = end
            elif kind == "else":
                fr["state"] = False if fr["done"] else (None if fr["state"] is None else True)
                fr["start"] = end
            else:
                stack.pop()
            continue
        if not active(): continue
        if kind == "define":
            m = re.match(r"([A-Za-z_]\w*)(\(|\s+|$)(.*)", expr)
            # a function-like macro has its '(' hard against the name
            if m and m.group(2) != "(" and not m.group(1).endswith(("_H", "_C")):
                val = m.group(3).strip()
                defs[m.group(1)] = "1" if val == "" else "(" + val + ")"
            continue
        if kind == "include":
            m = re.match(r'"([^"]+)"', expr)
            if not m: continue
            r = resolve_include(m.group(1))
            if r and r not in seen:
                seen.add(r)
                preprocess(r, defs, seen, units, order + 1)
    units.append((path, "".join(out)))

# ---------------------------------------------------------------- objects
OBJECTS = [
    {"key": "host",     "root": os.path.join(SRC, "host.c"),     "obj": "host.bpf.o",
     "define": "KESTREL_OBJ_HOST",
     "doc": "Host telemetry and the fabric's own programs: processes, credentials, files, "
            "sockets, unix IPC, syscalls, memory, block I/O, modules, BPF, signals, and the "
            "sweep, report, seed and clock programs. Needs CO-RE relocation to load."},
    {"key": "net_sock", "root": os.path.join(SRC, "net_sock.c"), "obj": "net_sock.bpf.o",
     "define": "KESTREL_OBJ_NET_SOCK",
     "doc": "The socket layer (l1_sock, ABI 23: who owns a socket, recorded at connect, bind, "
            "listen and accept) and the flows that have a local socket, where the kernel's own "
            "TCP state machine is the authority for lifecycle events. Always attached; needs "
            "CO-RE relocation since ABI 23."},
    {"key": "net_pkt",  "root": os.path.join(SRC, "net_pkt.c"),  "obj": "net_pkt.bpf.o",
     "define": "KESTREL_OBJ_NET_PKT",
     "doc": "The packet path: XDP for ingress, TC for egress and loopback, the L2 to L4 "
            "parsers and the L7 stage with its decoders. Attached only while a packet-path "
            "kind is enabled."},
]
for ob in OBJECTS:
    defs = {ob["define"]: "1", "__TARGET_ARCH_arm64": "1"}
    seen, units = {ob["root"]}, []
    preprocess(ob["root"], defs, seen, units, 0)
    ob["defs"] = defs
    ob["units"] = units                        # [(abs path, filtered text)]
    ob["files"] = [u[0] for u in units]

# ------------------------------------------------------------ map templates
ATTRS = {"type": r"__uint\(\s*type\s*,\s*([A-Za-z_0-9]+)\s*\)",
         "max_entries": r"__uint\(\s*max_entries\s*,\s*([^)]+)\)",
         "map_flags": r"__uint\(\s*map_flags\s*,\s*([^)]+)\)",
         "pinning": r"__uint\(\s*pinning\s*,\s*([^)]+)\)",
         "key_size": r"__uint\(\s*key_size\s*,\s*([^)]+)\)",
         "value_size": r"__uint\(\s*value_size\s*,\s*([^)]+)\)",
         "key": r"__type\(\s*key\s*,\s*([^)]+)\)",
         "value": r"__type\(\s*value\s*,\s*([^)]+)\)",
         "values": r"__array\(\s*values\s*,\s*([^)]+)\)"}

def parse_attrs(body):
    out = {}
    for k, rx in ATTRS.items():
        m = re.search(rx, body)
        if m: out[k] = re.sub(r"[\s\\]+", " ", m.group(1)).strip()
    return out

MAPDECL = re.compile(
    r"struct\s*\{(?P<body>.*?)\}\s*(?P<name>[A-Za-z_][A-Za-z_0-9]*)\s*SEC\(\"\.maps\"\)\s*;?",
    re.S)

def human_bytes_expr(s):
    """'16,777,216' -> '16 MiB each'; anything else is returned as written."""
    try:
        n = int(s.replace(",", ""))
    except ValueError:
        return s
    for u, d in (("GiB", 1 << 30), ("MiB", 1 << 20), ("KiB", 1 << 10)):
        if n >= d and n % d == 0: return f"{n // d} {u} each"
    return f"{n:,} B each"

def enum_defs():
    """Every enumerator's value, so a geometry written as KL_LAYER_MAX *
    KESTREL_PROTO_MAX resolves to the number the loader checks."""
    out = {}
    for e in ENUMS.values():
        nxt = 0
        for v in e["values"]:
            raw = (v.get("value") or "").strip()
            m = _INT.match(raw) if raw else None
            if m: nxt = int(m.group(1), 16) if m.group(1) else int(m.group(2))
            elif raw and SAFE.match(raw):
                try: nxt = int(eval(raw, {"__builtins__": {}}, {}))
                except Exception: pass
            out.setdefault(v["name"], str(nxt)); nxt += 1
    return out
_INT = re.compile(r"^\(?\s*(?:(0x[0-9a-fA-F]+)|(\d+))\s*[uUlL]*\s*\)?$")
ENUM_DEFS = enum_defs()

def resolve_consts(expr, defs):
    """Write a geometry expression as a number when the defines allow it."""
    e = expr
    for _ in range(8):
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b",
                    lambda m: defs.get(m.group(1), ENUM_DEFS.get(m.group(1), m.group(1))), e)
        if e2 == e: break
        e = e2
    e = re.sub(r"(\d)[uUlL]+\b", r"\1", e)
    if SAFE.match(e) and re.search(r"\d", e):
        try:
            v = eval(e, {"__builtins__": {}}, {})
            if isinstance(v, int) and v >= 0: return f"{v:,}"
        except Exception:
            pass
    return expr

# guards left standing above a declaration (object defines only)
def guards_at(dd, pos):
    stack = []
    for at, _e, kind, expr in dd:
        if at > pos: break
        if kind == "ifdef":    stack.append(expr.split()[0] if expr else "")
        elif kind == "ifndef": stack.append("!" + (expr.split()[0] if expr else ""))
        elif kind == "if":
            g = re.findall(r"defined\s*\(?\s*([A-Za-z_][A-Za-z_0-9]*)", expr)
            stack.append(g[0] if len(g) == 1 and "!" not in expr else "")
        elif kind in ("elif", "else"):
            if stack: stack[-1] = ""
        elif kind == "endif":
            if stack: stack.pop()
    return [g for g in stack if g and g.startswith("KESTREL_OBJ_")]

MAPS = {}      # name -> record
for ob in OBJECTS:
    for path, ftext in ob["units"]:
        for m in MAPDECL.finditer(ftext):
            name = m.group("name")
            attrs = parse_attrs(m.group("body"))
            rec = MAPS.get(name)
            if rec is None:
                t = TEXT[path]
                rec = MAPS[name] = {
                    "name": name,
                    "type": (attrs.get("type") or "").replace("BPF_MAP_TYPE_", ""),
                    "max_entries": resolve_consts(attrs.get("max_entries", ""), ob["defs"]),
                    "max_entries_src": attrs.get("max_entries", ""),
                    "map_flags": attrs.get("map_flags", ""),
                    "key": attrs.get("key", ""),
                    "value": attrs.get("value") or attrs.get("values", ""),
                    "key_size": attrs.get("key_size", ""),
                    "value_size": attrs.get("value_size", ""),
                    "decl_file": rel(path), "decl_line": lineno(t, m.start()),
                    "doc": doc_before(t, m.start()),
                    "gates": guards_at(DIRS[path], m.start()),
                    "objects": [], "producers": {}, "consumers": {},
                }
                inner = re.search(r"__array\(\s*values\s*,\s*struct\s*\{(.*?)\}\s*\)",
                                  m.group("body"), re.S)
                if inner:
                    ia = parse_attrs(inner.group(1))
                    rec["value"] = "%s of %s" % (
                        (ia.get("type") or "").replace("BPF_MAP_TYPE_", ""),
                        human_bytes_expr(resolve_consts(ia.get("max_entries", ""), ob["defs"])))
            if ob["key"] not in rec["objects"]:
                rec["objects"].append(ob["key"])

# ======================================================================
#  PROGRAMS
# ======================================================================
SEC_PROG = re.compile(r'SEC\(((?:"[^"]*"\s*)+)\)\s*\n?\s*int\s+([A-Za-z_]\w*)\s*\(')

def sec_name(lit):
    """The section a SEC() names, with adjacent string literals joined."""
    return "".join(re.findall(r'"([^"]*)"', lit))

def file_head_doc(path):
    """The comment that opens a source file: what its producer is."""
    t = TEXT[path].lstrip()
    if not t.startswith("/*"): return ""
    j = t.find("*/")
    return clean_prose(t[2:j]) if j > 0 else ""

def macro_bodies():
    out = {}
    for p in ALL:
        t = CODE[p]
        for m in re.finditer(r"^#define\s+([A-Za-z_]\w*)\(([^)]*)\)", t, re.M):
            i = m.end(); body = []
            for ln in t[i:].split("\n"):
                body.append(ln)
                if not ln.rstrip().endswith("\\"): break
            out.setdefault(m.group(1), []).append({
                "params": [x.strip() for x in m.group(2).split(",")],
                "body": "\n".join(body).replace("\\\n", "\n"), "file": rel(p)})
    return out
MACROS = macro_bodies()

def subst(s, params, args):
    """Expand a macro body: #param is stringified, params are replaced,
    then ## pastes."""
    for p_, a in zip(params, args):
        s = re.sub(r"(?<!#)#\s*\b%s\b" % re.escape(p_), '"' + a + '"', s)
        s = re.sub(r"\b%s\b" % re.escape(p_), a, s)
    return s.replace("##", "")

PROGS = []
for ob in OBJECTS:
    for path, ftext in ob["units"]:
        t = TEXT[path]
        head = file_head_doc(path)
        for m in SEC_PROG.finditer(ftext):
            sec = sec_name(m.group(1))
            if sec in (".maps", "license", "version"): continue
            own = doc_before(t, m.start())
            PROGS.append({"name": m.group(2), "sec": sec, "object": ob["key"],
                          "file": rel(path), "line": lineno(t, m.start()),
                          "doc": own if len(own) > 30 else head, "generated": ""})
        # a program a macro writes, instantiated on a line of its own
        for m in re.finditer(r"^([A-Z][A-Z0-9_]+)\(([^)]*)\)\s*;?\s*$", ftext, re.M):
            mac, args = m.group(1), [a.strip() for a in m.group(2).split(",")]
            for mm in MACROS.get(mac, []):
                if 'SEC("' not in mm["body"]: continue
                body = subst(mm["body"], mm["params"], args)
                for sm in SEC_PROG.finditer(body):
                    PROGS.append({"name": sm.group(2), "sec": sec_name(sm.group(1)),
                                  "object": ob["key"],
                                  "file": rel(path), "line": lineno(t, m.start()),
                                  "doc": doc_before(t, m.start()) or head, "generated": mac,
                                  "body_text": body})

# the loader's catalogue, for the bit each program holds in load_state
CATALOGUE = []
ct = read(os.path.join(ROOT, "rust", "contract.rs"))
cm = re.search(r"pub const CATALOGUE: \[&str; \d+\] = \[(.*?)\];", ct, re.S)
if cm:
    CATALOGUE = re.findall(r'"([A-Za-z_0-9]+)"', strip_comments(cm.group(1)))
CAT_INDEX = {n: i for i, n in enumerate(CATALOGUE)}

abi_m = re.search(r"#define\s+KESTREL_ABI_VER\s+(\d+)", TEXT[os.path.join(INC, "lib", "lib_types.h")])
ABI_VER = int(abi_m.group(1)) if abi_m else 0

# ======================================================================
#  ACCESS ANALYSIS
# ======================================================================
READ, WRITE = "consume", "produce"
HELPERS = {
    "bpf_map_lookup_elem":        (READ,  0),
    "bpf_map_lookup_percpu_elem": (READ,  0),
    "bpf_for_each_map_elem":      (READ,  0),
    "bpf_ringbuf_query":          (READ,  0),
    "bpf_tail_call":              (READ,  1),
    "bpf_redirect_map":           (READ,  0),
    "bpf_map_update_elem":        (WRITE, 0),
    "bpf_map_delete_elem":        (WRITE, 0),
    "bpf_map_push_elem":          (WRITE, 0),
    "bpf_map_pop_elem":           (WRITE, 0),
    "bpf_ringbuf_reserve":        (WRITE, 0),
    "bpf_ringbuf_output":         (WRITE, 0),
    "bpf_perf_event_output":      (WRITE, 1),
    "bpf_task_storage_delete":    (WRITE, 0),
    "bpf_sk_storage_delete":      (WRITE, 0),
    "bpf_timer_init":             (WRITE, 1),
    "bpf_task_storage_get":       ("storage", 0),
    "bpf_sk_storage_get":         ("storage", 0),
    "bpf_cgrp_storage_get":       ("storage", 0),
    "bpf_inode_storage_get":      ("storage", 0),
}
CALL = re.compile(r"\b(bpf_[a-z_0-9]+)\s*\(")

def split_args(s, start):
    depth, i, cur, out = 1, start, [], []
    while i < len(s) and depth:
        ch = s[i]
        if ch in "([": depth += 1
        elif ch in ")]":
            depth -= 1
            if depth == 0: break
        if depth == 1 and ch == ",":
            out.append("".join(cur).strip()); cur = []
        else:
            cur.append(ch)
        i += 1
    out.append("".join(cur).strip())
    return out, i

OUT_PARAM = (r"(?:__builtin_mem(?:set|cpy|move)|bpf_probe_read\w*|bpf_core_read\w*|"
             r"bpf_skb_load_bytes\w*|bpf_get_current_comm|bpf_d_path|bpf_get_func_arg\w*|"
             r"bpf_snprintf\w*|bpf_ringbuf_(?:reserve|output|submit|discard)|"
             r"bpf_map_(?:update|delete)_elem|bpf_get_stack\w*|bpf_timer_(?:init|set_callback|start)|"
             r"bpf_get_current_task_btf|bpf_probe_read_kernel_str|bpf_probe_read_user_str)")

def mutates(body, var):
    v = re.escape(var)
    member = rf"{v}\s*(?:->|\.)\s*\w+(?:\s*\[[^\]]*\])?(?:\s*(?:->|\.)\s*\w+(?:\s*\[[^\]]*\])?)*"
    pats = [
        rf"\*\s*{v}\s*(?:\+\+|--|[-+*/|&^%]?=(?!=))",
        rf"\*\s*{v}\s*=\s*\(",
        rf"(?<![\w.>]){member}\s*(?:\+\+|--|[-+*/|&^%]?=(?!=))",
        rf"(?:\+\+|--)\s*\*?\s*(?:{member}|{v})\b",
        rf"__sync_fetch_and_\w+\s*\(\s*&\s*(?:{member}|{v})\s*[,)]",
        rf"{OUT_PARAM}\s*\(\s*&?\s*(?:{member}|{v})\s*[,)\[]",
        rf"\*\s*{v}\s*=\s*\(\s*(?:struct|union)\s+\w+\s*\)\s*\{{",
        # bpf_skb_load_bytes(ctx, off, DEST, len): the destination is third
        rf"bpf_skb_load_bytes\w*\s*\([^,]+,[^,]+,\s*&?\s*(?:{member}|{v})\s*[,)\[]",
    ]
    return any(re.search(p, body) for p in pats)

def scan_calls(body):
    for m in CALL.finditer(body):
        args, end = split_args(body, m.end())
        yield m.group(1), args, m.start(), end

KW_NOT_FN = {"if","for","while","switch","return","sizeof","do","else","case",
             "defined","__builtin_expect","typeof","_Static_assert"}

def functions_in(text):
    """name -> [(body, start)] for every function definition in `text`."""
    out = {}
    for m in re.finditer(r"\)\s*\{", text):
        j = m.start(); depth = 0; i = j
        while i >= 0:
            if text[i] == ")": depth += 1
            elif text[i] == "(":
                depth -= 1
                if depth == 0: break
            i -= 1
        if i < 0: continue
        k = i - 1
        while k >= 0 and text[k] in " \t\n\\": k -= 1
        e = k + 1
        while k >= 0 and (text[k].isalnum() or text[k] == "_"): k -= 1
        name = text[k + 1:e]
        if not name or name in KW_NOT_FN or name[0].isdigit(): continue
        q = k
        while q >= 0 and text[q] in " \t\n\\*": q -= 1
        if q < 0 or not (text[q].isalnum() or text[q] in "_>)"): continue
        if text[q] == ">" or (q > 0 and text[q - 1] == "."): continue
        o = m.end() - 1; depth = 0; jj = -1
        for t_ in range(o, len(text)):
            if text[t_] == "{": depth += 1
            elif text[t_] == "}":
                depth -= 1
                if depth == 0: jj = t_; break
        if jj <= o: continue
        params = [re.sub(r"\[.*", "", p.strip()).split()[-1].lstrip("*") if p.strip() and p.strip() != "void" else ""
                  for p in text[i + 1: j].split(",")]
        out.setdefault(name, []).append((text[o + 1: jj], k + 1, params))
    return out

IDENT = re.compile(r"\b([A-Za-z_]\w*)\s*\(")
# the (layer, proto) row a call writes: ev_begin(KL_x, KP_x_y, ...) or any
# *emit*(…, KP_x_y, …) wrapper around it
EV_BEGIN = re.compile(r"\b\w*(?:ev_begin|emit)\w*\s*\([^;{}]*?\b(KP_[A-Z0-9_]+)")

KP_ALIAS = {}
for p in ALL:
    for m in re.finditer(r"^#define\s+(KP_[A-Z0-9_]+)\s+(KP_[A-Z0-9_]+)\b", CODE[p], re.M):
        KP_ALIAS[m.group(1)] = m.group(2)

def row_name(kp):
    """KP_L2_ETH -> l2.eth, KP_HOST_PROC -> host.proc."""
    m = re.match(r"KP_([A-Z0-9]+)_([A-Z0-9_]+)$", kp)
    return (m.group(1) + "." + m.group(2)).lower() if m else kp.lower()

def analyse(ob):
    """Per program of this object: {map: {roles, sites}}, rows emitted."""
    funcs, params_of = {}, {}
    for path, ftext in ob["units"]:
        label = rel(path)
        for nm, bodies in functions_in(ftext).items():
            for b, _at, ps in bodies:
                funcs.setdefault(nm, []).append((label, b))
                params_of.setdefault(nm, ps)
    # function-like macros are pseudo-functions reached by name
    for nm, defs_ in MACROS.items():
        for mm in defs_:
            if ")\n" in mm["body"] or "{" in mm["body"] or "(" in mm["body"]:
                funcs.setdefault(nm, []).append((mm["file"] + " (macro)", mm["body"]))
                params_of.setdefault(nm, mm["params"])
    # a macro-generated program's body, with its arguments substituted
    for pr in PROGS:
        if pr["object"] == ob["key"] and pr.get("body_text"):
            for nm, bodies in functions_in(pr["body_text"]).items():
                for b, _at, ps in bodies:
                    funcs.setdefault(nm, []).append((pr["file"] + " :: " + pr["generated"], b))
                    params_of.setdefault(nm, ps)

    def written_via_callee(tail, var, depth=0):
        """The looked-up pointer handed whole to a function that writes
        through the parameter it lands in: ssh_load(skb, sb, ...) fills sb.
        One level of callee is followed, two at most."""
        if depth > 2: return None
        v = re.escape(var)
        for m in re.finditer(r"\b([A-Za-z_]\w*)\s*\(", tail):
            callee = m.group(1)
            if callee not in funcs or callee not in params_of: continue
            args, _e = split_args(tail, m.end())
            for k, a in enumerate(args):
                if a.strip() != var: continue
                ps = params_of[callee]
                if k >= len(ps) or not ps[k]: continue
                for _l, cb in funcs[callee]:
                    if mutates(cb, ps[k]) or written_via_callee(cb, ps[k], depth + 1):
                        return callee
        return None

    results = {}
    for pr in [p for p in PROGS if p["object"] == ob["key"]]:
        roots = {pr["name"]}
        reach, queue = set(roots & set(funcs)), list(roots & set(funcs))
        while queue:
            fn = queue.pop()
            for _label, body in funcs.get(fn, []):
                for m in re.finditer(r"\b(\w{3,})\b", body):
                    nm = m.group(1)
                    if nm in funcs and nm not in reach:
                        reach.add(nm); queue.append(nm)
        hits, rows = {}, set()
        def note(mapname, role, site):
            e = hits.setdefault(mapname, {"roles": set(), "sites": []})
            e["roles"].add(role)
            if site not in e["sites"]: e["sites"].append(site)
        writes_ring = False
        for fn in sorted(reach):
            for label, body in funcs.get(fn, []):
                for em in EV_BEGIN.finditer(body):
                    # a proto enumerator, or an alias of one (KP_L1_SOCK is
                    # KP_HOST_SOCK by #define: the same row, the reader's name)
                    if em.group(1) in ENUM_DEFS or em.group(1) in KP_ALIAS:
                        rows.add(row_name(em.group(1)))
                if "bpf_ringbuf_output(" in body or "bpf_ringbuf_reserve(" in body:
                    writes_ring = True
                for helper, args, pos, end in scan_calls(body):
                    spec = HELPERS.get(helper)
                    if not spec: continue
                    role, idx = spec
                    if idx >= len(args): continue
                    a = args[idx].strip()
                    m = re.match(r"&\s*([A-Za-z_]\w*)$", a)
                    if not m: continue
                    mapname = m.group(1)
                    if mapname not in MAPS: continue
                    if role == "storage":
                        flags = args[3] if len(args) > 3 else ""
                        r = WRITE if "F_CREATE" in flags else READ
                        note(mapname, r, {"fn": fn, "file": label, "helper": helper})
                        if r == WRITE:
                            note(mapname, READ, {"fn": fn, "file": label, "helper": helper})
                        continue
                    note(mapname, role, {"fn": fn, "file": label, "helper": helper})
                    if helper.endswith(("lookup_elem", "lookup_percpu_elem")):
                        before = body[:pos].replace("\n", " ")
                        # `return bpf_map_lookup_elem(&ws, &k);` hands the
                        # caller a writable pointer: the get() helpers
                        after = body[end + 1:end + 12].lstrip()
                        if (re.search(r"\breturn\s*(?:\([^)]*\)\s*)?$", before)
                                and after.startswith(";")):
                            note(mapname, WRITE,
                                 {"fn": fn, "file": label,
                                  "helper": "lookup returned as a writable pointer"})
                            continue
                        mm = re.search(r"(?:^|[;{}()=])\s*([A-Za-z_][\w \t*]*?\b)?(\w+)\s*=\s*$", before)
                        if not mm: continue
                        decl, var = (mm.group(1) or ""), mm.group(2)
                        if not decl:
                            dm = re.search(r"\b((?:const\s+)?[\w]+(?:\s+\w+)*\s*\**)\s*%s\s*[;,=]"
                                           % re.escape(var), body)
                            decl = dm.group(1) if dm else ""
                        if "const" in decl: continue
                        tail = body[pos:]
                        if mutates(tail, var):
                            note(mapname, WRITE,
                                 {"fn": fn, "file": label, "helper": "lookup + write-through"})
                        elif re.search(r"return\s*(?:\([^)]*\)\s*)?%s\s*;" % re.escape(var), tail):
                            note(mapname, WRITE,
                                 {"fn": fn, "file": label,
                                  "helper": "lookup returned as a writable pointer"})
                        else:
                            callee = written_via_callee(tail, var)
                            if callee:
                                note(mapname, WRITE,
                                     {"fn": fn, "file": label,
                                      "helper": "lookup, written through by %s()" % callee})
        if writes_ring:
            for mapname, e in hits.items():
                if MAPS[mapname]["type"] == "ARRAY_OF_MAPS":
                    e["roles"].add(WRITE)
                    e["sites"].append({"fn": "ev_ring_write", "file": "src/lib/lib_emit.c",
                                       "helper": "bpf_ringbuf_output on the looked-up ring"})
        # BPF_F_RDONLY_PROG: the kernel refuses a write from any program, so
        # a looked-up pointer handed back is read-only whatever its C type
        for mapname, e in hits.items():
            if "RDONLY_PROG" in MAPS[mapname]["map_flags"] or MAPS[mapname]["type"] == "PROG_ARRAY":
                e["roles"].discard(WRITE)
                e["sites"] = [s for s in e["sites"] if not s["helper"].startswith("lookup")]
        results[pr["name"]] = (hits, sorted(rows), sorted(reach))
    return results

for ob in OBJECTS:
    res = analyse(ob)
    for pr in PROGS:
        if pr["object"] != ob["key"]: continue
        hits, rows, reach = res[pr["name"]]
        pr["rows"], pr["reach_n"] = rows, len(reach)
        for mapname, e in hits.items():
            rec = MAPS[mapname]
            if ob["key"] not in rec["objects"]: continue
            for role in e["roles"]:
                bucket = "producers" if role == WRITE else "consumers"
                rec[bucket].setdefault(pr["name"], [])
                for s in e["sites"]:
                    if s not in rec[bucket][pr["name"]]:
                        rec[bucket][pr["name"]].append(s)

# ======================================================================
#  EMIT
# ======================================================================
# ---- programs: type, attach method and the contract's notes -----------
PROG_TYPE = [
    (r"^xdp", "BPF_PROG_TYPE_XDP"), (r"^tc$", "BPF_PROG_TYPE_SCHED_CLS"),
    (r"^sockops", "BPF_PROG_TYPE_SOCK_OPS"), (r"^cgroup/", "BPF_PROG_TYPE_CGROUP_SOCK_ADDR"),
    (r"^tp_btf/", "BPF_PROG_TYPE_TRACING"), (r"^raw_tp/", "BPF_PROG_TYPE_RAW_TRACEPOINT"),
    (r"^tracepoint/", "BPF_PROG_TYPE_TRACEPOINT"), (r"^k(ret)?probe/", "BPF_PROG_TYPE_KPROBE"),
    (r"^iter/", "BPF_PROG_TYPE_TRACING"),
]
ATTACH = [
    (r"^xdp", "XDP on every physical device: native where the driver supports it, generic otherwise"),
    (r"^sockops|^cgroup/", "the root cgroup, BPF_F_ALLOW_MULTI"),
    (r"^tp_btf/|^raw_tp/", "a raw tracepoint link (BPF_RAW_TRACEPOINT_OPEN)"),
    (r"^tracepoint/", "perf_event_open(PERF_TYPE_TRACEPOINT), then BPF_LINK_CREATE"),
    (r"^k(ret)?probe/", "perf_event_open on the kprobe PMU, then BPF_LINK_CREATE"),
    (r"^iter/", "an iterator link, read to completion once at load"),
]
# docs/LOAD_CONTRACT.md sections 2, 15, 16 and 17, and rust/contract.rs
PROG_NOTES = {
    "l0_arm":        ("never attached", "run once per online CPU with PROG_TEST_RUN, so each CPU's sweep timer is created on the CPU whose coalesce rows it walks"),
    "l0_report":     ("never attached", "run once with PROG_TEST_RUN after load_state is filled: the stream's first record"),
    "l0_flush":      ("never attached", "run at exit, once per online CPU with PROG_TEST_RUN, after every cfg row is set to 0"),
    "l0_clock":      ("never attached", "run once with PROG_TEST_RUN after l0_report: the CLOCK record at load (ABI 9)"),
    "l0_clock_step": ("", "a CLOCK record on every step of the system clock (ABI 9)"),
    "l0_seed_task":  ("", "read to completion at step 5: one SNAPSHOT per process that existed before load"),
    "l0_seed_sock":  ("", "read to completion at step 5, after l0_seed_task: the owner of every socket that existed before load"),
    "l2_eth_tc_egress":  ("clsact egress on every physical device", ""),
    "l2_eth_tc_ingress": ("clsact ingress on lo; and on any device in place of XDP while an L7 kind is enabled", ""),
    "l3_tc_egress":  ("clsact egress on a device with no link header, in place of the Ethernet programs (ABI 16)", ""),
    "l3_tc_ingress": ("clsact ingress on a device with no link header, in place of the Ethernet programs (ABI 16)", ""),
    "l7_stage":      ("never attached", "installed at l7_progs[0] before net_pkt is attached; the entry programs reach it by tail call"),
    "l4_tcp_reset":  ("", "REFUSABLE: on a kernel whose BTF holds struct sock_common more than once the verifier refuses it and l4_tcp_reset_nosk is attached instead"),
    "l4_tcp_reset_nosk": ("", "the fallback for l4_tcp_reset: the same tracepoint, the record EV_UNOWNED; loaded and left unattached where l4_tcp_reset runs"),
}
# The names since ABI 23 (the host producers without their host_ prefix,
# the socket producer as l1_sock in net_sock), and the names before it.
_SECURITY_PATH = "needs CONFIG_SECURITY_PATH; skipped and recorded in load_state without it"
for new, old, note in [
    ("syscall_stamp", "host_sys_stamp", ("", "attached only when host.syscall SLOW (kind 15) is on: it runs on every syscall (ABI 21)")),
    ("syscall_slow", "host_sys_slow", ("", "attached only when host.syscall SLOW (kind 15) is on: it runs on every syscall (ABI 21)")),
    ("syscall_denied", "host_sys_denied", ("", "attached only when host.syscall DENIED (kind 10) is on: it runs on every syscall exit (ABI 6)")),
    ("wait_switch", "host_sched_switch", ("", "attached only when host.proc WAIT (12) or STUCK (14) is on (ABI 21)")),
    ("proc_profile", "host_sys_profile", ("", "attached only when host.proc PROFILE (kind 4) is on (ABI 8)")),
    ("cred_capable", "host_cap_capable", ("never at load", "Kestrel::focus_caps attaches it while a focus with FOCUS_CAPS is set (ABI 13)")),
    ("file_unlink", "host_file_unlink", ("", _SECURITY_PATH)),
    ("file_rename", "host_file_rename", ("", _SECURITY_PATH)),
    ("file_chmod", "host_file_chmod", ("", _SECURITY_PATH)),
    ("file_chown", "host_file_chown", ("", _SECURITY_PATH)),
    ("file_link", "host_file_link", ("", _SECURITY_PATH)),
    ("file_symlink", "host_file_symlink", ("", _SECURITY_PATH)),
    ("l1_sock_ops", "host_sock_ops", ("", "runs before l4_tcp_sockops in the same section: it is first in net_sock, so the owner it records is there for the L4 program (ABI 23)")),
]:
    PROG_NOTES[new] = note; PROG_NOTES[old] = note
for ab in ("connect4", "connect6", "bind4", "bind6", "sendmsg4", "sendmsg6", "recvmsg4", "recvmsg6"):
    PROG_NOTES["l1_sock_" + ab] = ("", "first in net_sock, so it runs before the l4_udp program in the same cgroup section and the owner it records is there for it (ABI 23)")
L7_DECODERS = {}
lm = re.search(r"pub const L7_DECODERS: .*?= \[(.*?)\];", ct, re.S)
if lm:
    for m in re.finditer(r'\("(\w+)",\s*(\d+),\s*&\[([\d, ]+)\]\)', lm.group(1)):
        L7_DECODERS[m.group(1)] = [int(x) for x in m.group(3).split(",")]

def attach_of(pr):
    nm = pr["name"]
    if nm in PROG_NOTES and PROG_NOTES[nm][0]:
        return PROG_NOTES[nm][0]
    if nm in L7_DECODERS:
        slots = ", ".join(str(s) for s in L7_DECODERS[nm])
        return "never attached: tail-called by l7_stage from l7_progs slot %s" % slots
    for rx, txt in ATTACH:
        if re.search(rx, pr["sec"]): return txt
    return ""

def note_of(pr):
    nm = pr["name"]
    if nm in PROG_NOTES and PROG_NOTES[nm][1]:
        return PROG_NOTES[nm][1]
    if nm in L7_DECODERS:
        return "left out when its row has no kind on: its classes are then named by l7.ident and not decoded (ABI 17)"
    return ""

# ---- map families ---------------------------------------------------------
FAMILY = {
    "Configuration": (["cfg", "cfg_global"],
        "Gate masks and global knobs the loader writes from kestrel.yaml at step 3; RDONLY_PROG, so no producer can silence itself or change the window."),
    "Event stream": (["rings"],
        "One 16 MiB ring buffer per CPU, filled by the loader before any attach; every record leaves the kernel through it. A CPU with no ring silently loses every event on it."),
    "Emit path": (["scratch", "depth"],
        "Per-CPU working state of emit(): the event under construction, one slot per nesting level, and the level itself."),
    "Coalescing": (["coalesce"],
        "The per-CPU fold table: a deduplicated or shed event is counted here, and the sweep writes one summary per entity per window."),
    "Sweep": (["sweep_timers", "sys_flush"],
        "The self-rearming timer per CPU that walks coalesce each window, and what the ABI 21 sweep flushes."),
    "Ownership": (["sk_owner", "proc_ctx", "task_ctx", "flow_owner"],
        "Who owns a socket, a process, a thread or a TCP flow: the identity every network record is joined to."),
    "Fabric state": (["load_state", "self_info", "own_objects", "last_signal"],
        "What the loader recorded at load, what l0_seed_task wrote about the daemon itself, and what the next daemon reads from the pin."),
    "Counters": (["stats", "stats_shadow", "sys_rates", "sys_rates_shadow", "sys_active", "rates", "rates_shadow"],
        "Per-CPU running counters and their value at the last sweep, so a flush emits deltas and an idle row emits nothing."),
    "Response": (["focus", "contain", "contain_allow", "denied_mark"],
        "The daemon's focus and containment (ABI 12): pinned under /sys/fs/bpf/kestrel, read by the emit path and the cgroup hooks."),
    "Watch lists": (["file_watch", "name_watch", "env_watch", "doh_resolvers", "l7_port_class"],
        "What the loader resolved from filters.d at step 3: watched inodes, names, environment variables, DoH resolver digests and port classes."),
    "DNS answers": (["dns_seen"],
        "An answered address to the digest of the name that named it (ABI 14): written by the DNS parser, read at connect and SYN_SENT."),
    "Workspace": (["pkt_ws", "l7_buf", "l7_walk", "ssh_buf", "file_ws", "exec_ws", "fold_ws"],
        "Per-CPU scratch a producer claims for one event; holds nothing between events."),
    "L7 stage": (["l7_progs", "l7_flows"],
        "The tail-call table the entry programs reach l7_stage and the decoders through, and the flows the stage has classified."),
    "Per-entity state": (["exit_seen", "mmap_seen", "wx_hist", "io_pending", "wait_ctx", "d_wait", "sess_ctx", "sys_profile"],
        "What a producer remembers between two hooks of the same process, thread, request or mapping."),
}
FAMILY_OF = {}
for fam, (names, blurb) in FAMILY.items():
    for n in names: FAMILY_OF[n] = (fam, blurb)

# docs/LOAD_CONTRACT.md section 1: pinned by the daemon, and nothing else
PINNED = {"last_signal": "by the daemon at /sys/fs/bpf/kestrel/last_signal, read by the next daemon",
          "focus": "by the daemon at /sys/fs/bpf/kestrel/focus, so kestrelctl can write a focus",
          "contain": "by the daemon at /sys/fs/bpf/kestrel/contain, so kestrelctl can write a containment",
          "contain_allow": "by the daemon at /sys/fs/bpf/kestrel/contain_allow"}

def flow_of(rec):
    p, c = bool(rec["producers"]), bool(rec["consumers"])
    if p and c:  return "kernel-state"
    if p:        return "kernel-output"
    if c:        return "control-input"
    return "declared-only"

FLOW_LABEL = {
    "kernel-state":  "Written and read in kernel",
    "kernel-output": "Written in kernel, drained by userspace",
    "control-input": "Written by userspace, read in kernel",
    "declared-only": "Declared, no reachable in-kernel access",
}

# ---------------------------------------------------------------- prose
FILE_RE    = r"[\w][\w/.-]*\.(?:c|h|rs|py|sh|md)"
FILE_TOKEN = re.compile(r"(?<![\w/.-])(" + FILE_RE + r")('s)?(?![\w/-])(?!\.\w)")

def clean_prose_files(text):
    """Rewrite a quoted comment so it names no source file: the page's unit
    is the program and the map, not the file. A removal takes the
    preposition or separator that introduced it, so the sentence parses.
    Research notes (*.md under docs/) are citations and stay."""
    if not text or "." not in text:
        return text
    def swap(m):
        f = m.group(1)
        if f.endswith(".md"): return m.group(0)
        return "\x00"
    out = FILE_TOKEN.sub(swap, text)
    if "\x00" not in out:
        return out
    out = re.sub(r"\s*\(\s*\x00[^()]*\)", "", out)
    out = re.sub(r"\s+(?:in|by|from|at|to|of|under|with|via|than|inside|on|and|is|see)\s+\x00",
                 "", out, flags=re.IGNORECASE)
    out = re.sub(r"\s*[,;]\s*\x00", "", out)
    out = re.sub(r"\x00\s*[,;:]\s*", "", out)
    out = out.replace("\x00", "")
    out = re.sub(r"\(\s+", "(", out)
    out = re.sub(r"\s+([,.;:)])", r"\1", out)
    out = re.sub(r"\s{2,}", " ", out)
    return out.strip()

# ---- programs ----------------------------------------------------------
PROGS.sort(key=lambda p: (CAT_INDEX.get(p["name"], 999), p["name"]))
OBJ = {o["key"]: o for o in OBJECTS}
prog_out, prog_index = [], {}
for pr in PROGS:
    ptype = next((t for rx, t in PROG_TYPE if re.search(rx, pr["sec"])), "")
    prog_index[pr["name"]] = len(prog_out)
    prog_out.append({
        "id": len(prog_out), "name": pr["name"], "file": pr["file"], "line": pr["line"],
        "base": OBJ[pr["object"]]["obj"], "domain": pr["object"],
        "prog_type": ptype, "attach": [pr["sec"]], "attach_count": 1,
        "attach_how": attach_of(pr), "note": note_of(pr),
        "catalogue": CAT_INDEX.get(pr["name"], -1),
        "rows": pr["rows"], "generated": pr["generated"],
        "gates": [OBJ[pr["object"]]["define"]],
        "doc": clean_prose_files(pr["doc"])[:700],
        "produces": [], "consumes": [],
    })

# ======================================================================
#  EXAMPLES — a worked value for every key and value member
#
#  The example literals are ILLUSTRATIVE: constructed to show the encoding,
#  not captured from a run. What they decode TO is not invented -- bit names,
#  enum names and their values are read out of the headers, so an example
#  either decodes against real constants or says only what the C type says.
#  `basis` records which of those it was, and the About panel repeats it.
# ======================================================================
_SHIFT = re.compile(r"^\(?\s*1\s*[uUlL]*\s*<<\s*\(?\s*(\d+)\s*\)?\s*\)?$")

CONSTS, FAMILIES = {}, {}

def build_constant_tables():
    for p in ALL:
        for m in re.finditer(r"^#define\s+([A-Z][A-Z0-9_]+)\s+([^\n/]+)", CODE[p], re.M):
            name, raw = m.group(1), m.group(2).strip()
            v, mm = None, _INT.match(raw)
            if mm:
                v = int(mm.group(1), 16) if mm.group(1) else int(mm.group(2))
            else:
                ms = _SHIFT.match(raw)
                if ms: v = 1 << int(ms.group(1))
            if v is not None:
                CONSTS.setdefault(name, v)
    # a family is the longest prefix (ending in '_') that at least three
    # constants share, excluding the kernel's own vocabularies
    skip = ("BPF_", "ETH_P_", "TC_ACT_", "XDP_", "AF_", "IPPROTO_", "PF_", "SOCK_", "ARPHRD_")
    by_prefix = {}
    for name in CONSTS:
        if name.startswith(skip): continue
        parts = name.split("_")
        for i in range(1, len(parts)):
            by_prefix.setdefault("_".join(parts[:i]) + "_", set()).add(name)
    roots = sorted((p for p, s in by_prefix.items() if len(s) >= 3), key=len, reverse=True)
    for name, v in CONSTS.items():
        for root in roots:
            if name.startswith(root) and name != root.rstrip("_"):
                FAMILIES.setdefault(root, {})[name[len(root):]] = v
                break
    for root, vals in list(FAMILIES.items()):
        nz = [v for v in vals.values() if v]
        FAMILIES[root] = {
            "values": vals,
            "bitmask": bool(nz) and all(v & (v - 1) == 0 for v in nz)
                       and len(set(nz)) == len(nz) and len(nz) >= 2,
        }

def enum_pairs(name):
    e = ENUMS.get(name)
    if not e: return []
    out, nxt = [], 0
    for v in e["values"]:
        raw = (v.get("value") or "").strip()
        m = _INT.match(raw) if raw else None
        if m: nxt = int(m.group(1), 16) if m.group(1) else int(m.group(2))
        out.append((v["name"], nxt)); nxt += 1
    return out

# (struct, member) -> family root or "enum:<name>", where the header's own
# comment does not already say which vocabulary the member holds.
FIELD_FAMILY = {
    ("ev_hdr", "layer"): "enum:kestrel_layer",
    ("event", "layer"): "enum:kestrel_layer",
    ("cfg_row", "enabled"): None,
}
COMMENT_FAMILY = re.compile(r"\b([A-Z][A-Z0-9]+(?:_[A-Z0-9]+)*_)\*|\benum (\w+)")

def const_family_of(struct, field):
    key = (struct, field["name"].split("[")[0])
    if key in FIELD_FAMILY: return FIELD_FAMILY[key]
    m = COMMENT_FAMILY.search(field.get("note") or "")
    if m:
        if m.group(2) and m.group(2) in ENUMS: return "enum:" + m.group(2)
        if m.group(1) in FAMILIES: return m.group(1)
    t = field["type"]
    m = re.match(r"(?:const\s+)?enum\s+(\w+)$", t)
    if m and m.group(1) in ENUMS: return "enum:" + m.group(1)
    return None

WIDTH = {"__u8": 8, "__s8": 8, "__u16": 16, "__s16": 16, "__u32": 32, "__s32": 32,
         "__u64": 64, "__s64": 64, "int": 32, "unsigned int": 32, "char": 8,
         "bool": 8, "long": 64, "unsigned long": 64, "__be16": 16, "__be32": 32}

def _art(bits):
    return "An" if bits == 8 else "A"

def human_ns(ns):
    if ns < 1000: return f"{ns} ns"
    if ns < 1_000_000: return f"{ns/1000:.1f} µs"
    if ns < 1_000_000_000: return f"{ns/1e6:.1f} ms"
    if ns < 60_000_000_000: return f"{ns/1e9:.2f} s"
    return f"{ns/6e10:.1f} min"

def human_bytes(n):
    for u, d in (("GiB", 1 << 30), ("MiB", 1 << 20), ("KiB", 1 << 10)):
        if n >= d: return f"{n/d:.1f} {u}"
    return f"{n} B"

TOKENS = {
    "rx": "received", "tx": "transmitted", "sys": "syscall", "unint": "uninterruptible",
    "ns": "nanoseconds", "ts": "timestamp", "ino": "inode number", "inum": "inode number",
    "tgid": "thread-group id", "pid": "process id", "ppid": "parent process id",
    "tid": "thread id", "uid": "user id", "gid": "group id", "euid": "effective user id",
    "cgroup": "cgroup", "dev": "device", "lat": "latency", "hist": "histogram",
    "errno": "errno", "prot": "protection bits", "vma": "virtual memory area",
    "seq": "sequence number", "gen": "generation", "sum": "sum", "max": "maximum",
    "min": "minimum", "cnt": "count", "n": "count", "len": "length", "sz": "size",
    "src": "source", "dst": "destination", "addr": "address", "port": "port",
    "proto": "protocol", "iface": "interface", "if": "interface", "blk": "block",
    "acc": "accumulator", "run": "run length", "shad": "shadow", "scrat": "scratch",
    "nr": "syscall number", "aux": "auxiliary value", "ver": "version",
    "mnt": "mount", "sb": "superblock", "exe": "executable", "fp": "fingerprint",
    "qname": "query name", "cookie": "socket cookie", "kind": "kind", "digest": "digest",
}
def describe_name(name):
    parts = [p for p in re.split(r"[_\d]+", name.split("[")[0]) if p]
    return " ".join(TOKENS.get(p, p) for p in parts)

TYPES_SEEN = set()

def example_for(struct, f):
    """(example literal, what it decodes to, basis)."""
    name = f["name"].split("[")[0]
    arr  = re.search(r"\[([^\]]*)\]", f["name"])
    ty   = re.sub(r"^const\s+", "", f["type"]).strip()
    note = (f.get("note") or "")
    fam  = const_family_of(struct, f)

    nt = note.strip().rstrip(".")
    if re.fullmatch(r"[A-Z][A-Z0-9_]+", nt) and nt in CONSTS:
        return str(CONSTS[nt]), f"{nt} = {CONSTS[nt]}.", "constants"

    if name.startswith(("_pad", "_rsv", "_reserved", "pad")) or re.fullmatch(r"pad\d*", name):
        return "0", "Padding. Never written; not part of the ABI.", "type"

    if ty.startswith(("struct ", "union ")):
        inner = ty.split()[-1]
        if inner == "bpf_timer":
            return "", "A bpf_timer: opaque to userspace, armed by bpf_timer_init and bpf_timer_start.", "type"
        return "", f"The members of {ty}" + (f", listed under its own entry." if inner in TYPES_SEEN else "."), "type"

    if fam and fam.startswith("enum:"):
        pairs = [(n, v) for n, v in enum_pairs(fam[5:]) if not n.endswith(("_COUNT", "_MAX", "_SLOTS", "_N"))]
        if pairs:
            n, v = pairs[min(1, len(pairs) - 1)]
            rest = ", ".join(f"{v2}={n2}" for n2, v2 in pairs[:5])
            return str(v), f"{n} — one of {rest}", "constants"
    if fam and fam in FAMILIES:
        vals = {k: v for k, v in FAMILIES[fam]["values"].items()
                if not k.endswith(("MAX", "COUNT", "SLOTS", "CAP", "NONE", "ROWS", "BYTES"))}
        if vals:
            if FAMILIES[fam]["bitmask"]:
                picked = sorted(vals.items(), key=lambda kv: kv[1])[:2]
                val = 0
                for _n, v in picked: val |= v
                names = " | ".join(fam + n for n, _v in picked)
                allnames = ", ".join(f"{fam}{n}=0x{v:x}" for n, v in
                                     sorted(vals.items(), key=lambda kv: kv[1])[:6])
                return f"0x{val:04x}", f"{names}. Bits: {allnames}", "constants"
            picked = sorted(vals.items(), key=lambda kv: kv[1])
            n, v = picked[min(1, len(picked) - 1)]
            rest = ", ".join(f"{v2}={n2}" for n2, v2 in picked[:5])
            return str(v), f"{fam}{n} — one of {rest}", "constants"

    if arr and ty in ("__u8", "char", "unsigned char"):
        if re.search(r"path|name|comm|exe|interp|args|filename|cwd|host|sni|argv|thread|ua|banner|qname", name):
            return '"/usr/bin/curl"', f"A NUL-terminated string, at most {arr.group(1)} bytes.", "type"
        if re.search(r"addr|ip|a$|mac|src|dst", name):
            return "c0 a8 01 0a …", f"{arr.group(1)} address bytes as on the wire.", "type"
        return "00 00 00 00 …", f"{arr.group(1)} raw bytes.", "type"
    if arr:
        return "[0, 0, …]", f"{arr.group(1)} × {ty}.", "type"

    bits = WIDTH.get(ty, 32)
    cap  = (1 << bits) - 1
    sat  = "saturates" in note.lower()

    if name.endswith(("_ns", "_boottime", "_ts")) or name in ("now", "enter_ts", "ts", "expires", "until"):
        stamp = bool(re.search(r"boottime|_ts$|^ts$|^created|^first|^last|start|enter|emit|_at$|expires|until", name))
        v = 812_345_678_901 if stamp else 1_450_000
        what = ("a point in time on the boot clock" if stamp else "a duration")
        return str(v), f"{human_ns(v)} — {what}, in nanoseconds, {bits}-bit.", "unit"
    if name.endswith(("_us",)):
        return "12000", "12.0 ms — a duration in microseconds.", "unit"
    if name.endswith(("_ms",)):
        return "1000", "1.00 s — a duration in milliseconds.", "unit"
    if name.endswith("_bytes") or name.startswith("bytes_") or name in ("count_bytes", "pos", "size"):
        v = 1_048_576
        return str(v), f"{human_bytes(v)} — a byte count, {bits}-bit.", "unit"
    if name.endswith(("_ino", "_inum")) or name in ("ino", "dir_ino", "inum"):
        return "3407875", f"An inode number, {bits}-bit. Stable across rename and hardlink.", "unit"
    if name.endswith(("_id",)) or name in ("cgroup_id", "node_id", "flow_id"):
        return "12406", f"An opaque {bits}-bit id; compare it, do not interpret it.", "unit"
    if name.endswith(("_hash", "cookie", "_digest", "digest", "lineage")) or name.startswith("hash"):
        return "0x4c968a90ace3649b", f"A {bits}-bit digest; an identity to join on, not a value to read.", "unit"
    if re.search(r"^(?:owner_|target_|self_)?(?:pid|tgid|ppid|tid|[eu]?uid|gid)(?:_at_exec)?$", name):
        return "1742", f"{describe_name(name).capitalize()}, {bits}-bit.", "unit"
    if name.endswith(("_port",)) or name in ("sport", "dport", "port", "lport", "rport"):
        return "443", f"A TCP/UDP port, {bits}-bit.", "unit"
    if name == "magic":
        return "0x9123683e", "The filesystem's s_magic (statfs f_type): 0x9123683e is btrfs.", "unit"
    if name in ("nr", "pending_nr"):
        return "59", "A syscall number on this architecture: 59 is execve on x86_64.", "unit"
    if re.search(r"count|hits|_n$|^n$|fanout|dests|depth|entries|events|switches|errors|drops|^level$|since_wake", name):
        v = 7
        extra = f" Saturates at {cap}: it is not decremented." if sat else ""
        return str(v), f"{_art(bits)} {bits}-bit counter — {describe_name(name)}.{extra}", "unit"
    if name.endswith(("_len", "_size")) or name in ("len",):
        return "64", f"A length in bytes, {bits}-bit.", "unit"
    if name in ("seq", "generation") or name.endswith(("_generation", "_seq", "_version")):
        return "3", f"{_art(bits)} {bits}-bit {describe_name(name)}; it only moves forward.", "unit"
    if name == "ver":
        return str(ABI_VER), f"KESTREL_ABI_VER: the ABI this record was written under.", "constants"

    return "0", f"{describe_name(name).capitalize()} — {bits}-bit {'unsigned' if ty.startswith('__u') or ty.startswith('__be') or ty in ('unsigned int','unsigned long') else 'signed'}.", "type"

TYPES = {}
build_constant_tables()

def _member(struct, f):
    ex, dec, basis = example_for(struct, f)
    return {"type": f["type"], "name": f["name"], "bits": f["bits"],
            "note": clean_prose_files(f["note"])[:240],
            "example": ex, "decoded": dec, "basis": basis}

def want_type(t):
    t = (t or "").strip()
    mm = re.match(r"(?:const\s+)?struct\s+([A-Za-z_]\w*)", t)
    if not mm: return
    nm = mm.group(1)
    if nm in TYPES or nm not in STRUCTS: return
    TYPES_SEEN.add(nm)
    st = STRUCTS[nm]
    TYPES[nm] = {"name": "struct " + nm, "file": st["file"], "line": st["line"],
                 "doc": clean_prose_files(st["doc"])[:700],
                 "fields": [_member(nm, f) for f in st["fields"]]}
    for f in st["fields"]:
        want_type(f["type"])

# ---- maps --------------------------------------------------------------
map_out = []
NOBJ = len(OBJECTS)
for name, rec in sorted(MAPS.items()):
    fam, blurb = FAMILY_OF.get(name, ("State", ""))
    want_type(rec["key"]); want_type(rec["value"])
    prods = sorted(rec["producers"].items(), key=lambda kv: prog_index.get(kv[0], 999))
    cons  = sorted(rec["consumers"].items(), key=lambda kv: prog_index.get(kv[0], 999))
    n = len(rec["objects"])
    scope = "shared" if n == NOBJ else ("per-object" if n > 1 else "object")
    owners = sorted({prog_index[p] for p in prog_index
                     if PROGS[prog_index[p]]["object"] in rec["objects"]})
    map_out.append({
        "name": name, "scope": scope, "type": rec["type"],
        "family": fam, "blurb": blurb,
        "max_entries": rec["max_entries"], "max_entries_src": rec["max_entries_src"],
        "map_flags": rec["map_flags"],
        "pinned": PINNED.get(name, ""),
        "key": rec["key"] or rec["key_size"], "value": rec["value"] or rec["value_size"],
        "file": rec["decl_file"], "line": rec["decl_line"],
        "doc": clean_prose_files(rec["doc"])[:900], "gates": rec["gates"], "macro": "",
        "objects": [OBJ[o]["obj"] for o in rec["objects"]],
        "flow": flow_of(rec),
        "owners": owners,
        "producers": [{"prog": prog_index[f], "sites": st[:6]} for f, st in prods if f in prog_index],
        "consumers": [{"prog": prog_index[f], "sites": st[:6]} for f, st in cons if f in prog_index],
    })
for i, m in enumerate(map_out):
    for e in m["producers"]: prog_out[e["prog"]]["produces"].append(i)
    for e in m["consumers"]: prog_out[e["prog"]]["consumes"].append(i)

objects_out = [{"key": o["key"], "file": o["obj"], "doc": o["doc"],
                "programs": sum(1 for p in prog_out if p["domain"] == o["key"]),
                "maps": sum(1 for m in map_out if o["obj"] in m["objects"])}
               for o in OBJECTS]

data = {
    "generated": datetime.date.today().isoformat(),
    "source": SOURCE_LABEL,
    "abi": ABI_VER,
    "method": ("Parsed from the sources. Each of the three objects (host, net_sock, net_pkt) "
               "is a unity build, so its root was preprocessed the way clang sees it: every "
               "#include followed in order, #if evaluated with the object's own KESTREL_OBJ_* "
               "define and KESTREL_TEST unset, which leaves the test fixtures out. A map is "
               "every `SEC(\".maps\")` declaration left after that; one that survives in all "
               "three objects is created once by the loader and shared by descriptor, one that "
               "survives in a single object belongs to it. A program is a SEC() entry, written "
               "out or generated by L7_DECODER. An edge is a map helper call reached from the "
               "entry through the object's static inline and global functions, bpf_loop and "
               "bpf_timer callbacks and function-like macros; a write is an update / delete / "
               "ringbuf output / timer init / storage get with F_CREATE, or a lookup whose "
               "result the same function writes through or returns as a writable pointer. "
               "Userspace is not analysed: what the loader and the daemon write is said in "
               "each map's family note, from docs/LOAD_CONTRACT.md."),
    "counts": {"maps": len(map_out), "programs": len(prog_out), "objects": len(OBJECTS),
               "catalogue": len(CATALOGUE),
               "members": sum(len(t["fields"]) for t in TYPES.values()),
               "basis": {k: sum(1 for t in TYPES.values() for f in t["fields"]
                                if f["basis"] == k)
                         for k in ("constants", "source", "unit", "type")},
               "shared": sum(1 for m in map_out if m["scope"] == "shared"),
               "edges": sum(len(m["producers"]) + len(m["consumers"]) for m in map_out)},
    "flow_label": FLOW_LABEL,
    "objects": objects_out,
    "programs": prog_out, "maps": map_out, "types": TYPES,
}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("const SIGNALS = ")
    json.dump(data, f, separators=(",", ":"), ensure_ascii=False)
    f.write(";\n")

missing = [n for n in CATALOGUE if n not in prog_index]
extra   = [p["name"] for p in prog_out if p["catalogue"] < 0]
print(f"{OUT}: ABI {ABI_VER}, {data['counts']['maps']} maps ({data['counts']['shared']} shared), "
      f"{data['counts']['programs']} programs, {data['counts']['edges']} producer/consumer edges, "
      f"{os.path.getsize(OUT)} bytes")
if missing: print("  catalogue programs not found in the sources:", ", ".join(missing))
if extra:   print("  programs not in the catalogue:", ", ".join(extra))
