#!/usr/bin/env python3
"""Build assets/data/signals.js from the eBPF sources in crates/bpf.

Emits `const SIGNALS = {...};` -- the load-as-a-script convention data.js,
campaigns.js and ebpf.js use, denormalised so the pages render without any
further joining: every map carries its declaration, its key and value shape,
and the programs that write it (producers) or read it (consumers) with the
call site that proves each edge.

WHAT IS PARSED

  * Every `SEC(".maps")` declaration, whether written out in a header or a
    source or generated by a KESTREL_DEFINE_* / TELEMETRY_DEFINE_* macro
    (nested macros are expanded, so KESTREL_DEFINE_PATH_TABLE's side table
    appears under its own name).
  * Each program object's #include graph and its KESTREL_* feature gates,
    evaluated with a small #if/#ifdef evaluator, so a header's map belongs
    only to the objects that actually declare it.
  * Map-helper calls reached from a SEC() entry, a bpf_timer callback or a
    bpf_loop callback. A WRITE is an update / delete / push / ringbuf
    reserve / ringbuf output / storage get with F_CREATE, or a lookup whose
    result the same function writes through or returns as a writable
    pointer. Everything else that touches the map is a READ.

LIMITS, stated so the pages can state them

  * Gates only a kernel-capability probe sets (KESTREL_NO_*) are taken as
    unset: this is the capable-kernel build.
  * Reachability follows calls and macro bodies; a callee hidden behind
    token pasting is reached by name, which over-approximates slightly.
  * Userspace is not analysed. A map with in-kernel readers and no in-kernel
    writer is a control-plane input; one with writers and no readers is
    drained by userspace. Both are reported as such.

    python3 assets/data/source/signals_to_js.py \\
        ../crates/bpf assets/data/signals.js
"""
import datetime, json, os, re, sys

ROOT = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else "../crates/bpf")
OUT  = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else "assets/data/signals.js")
INC  = os.path.join(ROOT, "include")
BPF  = os.path.join(ROOT, "bpf")

rel  = lambda p: os.path.relpath(p, ROOT)
read = lambda p: open(p, encoding="utf-8", errors="replace").read()

# ------------------------------------------------------------------- sources
headers, sources = [], []
for base, dirs, files in os.walk(INC):
    dirs[:] = [d for d in dirs if d != "generated"]
    headers += [os.path.join(base, f) for f in files if f.endswith(".h")]
for base, _d, files in os.walk(BPF):
    sources += [os.path.join(base, f) for f in files if f.endswith(".c")]
headers.sort(); sources.sort()
TEXT = {p: read(p) for p in headers + sources}
BYNAME = {os.path.basename(p): p for p in headers}
BYREL  = {os.path.relpath(p, INC): p for p in headers}

def strip_comments(s):
    """Blank out comments, preserving every offset and newline."""
    out, i, n = list(s), 0, len(s)
    def blank(a, b):
        for k in range(a, b):
            if out[k] != "\n": out[k] = " "
    while i < n:
        if s.startswith("/*", i):
            j = s.find("*/", i + 2); j = n if j < 0 else j + 2
            blank(i, j); i = j
        elif s.startswith("//", i):
            j = s.find("\n", i); j = n if j < 0 else j
            blank(i, j); i = j
        elif s[i] in "\"'":
            q = s[i]; i += 1
            while i < n and s[i] != q:
                if s[i] == "\\": i += 1
                i += 1
            i += 1
        else:
            i += 1
    return "".join(out)

CODE = {p: strip_comments(t) for p, t in TEXT.items()}
lineno = lambda text, pos: text.count("\n", 0, pos) + 1

def clean_prose(body):
    lines = [re.sub(r"^\s*\*\s?", "", ln).strip() for ln in body.split("\n")]
    return re.sub(r"\s+", " ", " ".join(x for x in lines if x)).strip()

def doc_before(text, pos):
    """The comment block above `pos`, looking past #if/#define and blank lines."""
    head = text[:pos]
    skipped = 0
    while True:
        stripped = head.rstrip()
        if stripped.endswith("*/"):
            start = stripped.rfind("/*")
            if start < 0: return ""
            return clean_prose(stripped[start + 2: -2])
        nl = stripped.rfind("\n")
        line = stripped[nl + 1:].strip()
        if skipped >= 3 or (line and not re.match(r"#\s*(if|ifdef|ifndef|else|elif|endif)\b", line)):
            return ""
        skipped += 1
        head = stripped[:nl + 1]

# -------------------------------------------------------------- struct/enums
STRUCTS, ENUMS = {}, {}
FIELD_RE = re.compile(
    r"^(?P<type>(?:const |volatile |unsigned |signed |struct |union |enum )*"
    r"[A-Za-z_][A-Za-z_0-9]*\s*\**)\s*(?P<name>[A-Za-z_][A-Za-z_0-9]*)"
    r"(?P<arr>(?:\s*\[[^\]]*\])*)\s*(?::\s*(?P<bits>\d+))?$")
SKIP_TY = {"return", "if", "else", "static", "_Static_assert", "typedef"}

def comments_in(chunk):
    """[(start, text)] for every comment in `chunk`, in order."""
    out = []
    for m in re.finditer(r"/\*(.*?)\*/|//([^\n]*)", chunk, re.S):
        out.append((m.start(), clean_prose(m.group(1) or m.group(2))))
    return out

def parse_struct_body(body):
    """Members of a struct, each with the comment the source keeps beside it.

    A comment that sits on the same line as the PREVIOUS member's semicolon is
    that member's trailing note, not the next one's opening remark -- without
    that split, `__u64 x; /* about x */` would document the field after x."""
    fields, bare, start = [], strip_comments(body), 0
    for m in re.finditer(r";", bare):
        raw, start = body[start:m.start()], m.end()
        if not raw.strip(): continue
        nl = raw.find("\n")
        notes, trailing = [], []
        for at, txt in comments_in(raw):
            (trailing if (nl >= 0 and at < nl) else notes).append(txt)
        if trailing and fields:
            fields[-1]["note"] = re.sub(r"\s+", " ",
                (fields[-1]["note"] + " " + " ".join(trailing)).strip())
        clean = re.sub(r"\s+", " ", strip_comments(raw)).strip()
        if not clean or "(" in clean: continue
        fm = FIELD_RE.match(clean)
        if not fm: continue
        ty = re.sub(r"\s+", " ", fm.group("type")).strip()
        if ty.split()[0] in SKIP_TY: continue
        fields.append({"type": ty,
                       "name": fm.group("name") + (fm.group("arr") or "").replace(" ", ""),
                       "bits": fm.group("bits"),
                       "note": re.sub(r"\s+", " ", " ".join(notes)).strip()})
    return fields

for p in headers + sources:
    t = TEXT[p]
    for m in re.finditer(r"\bstruct\s+([A-Za-z_][A-Za-z_0-9]*)\s*\{", t):
        name, i, depth = m.group(1), m.end() - 1, 0
        for j in range(i, len(t)):
            if t[j] == "{": depth += 1
            elif t[j] == "}":
                depth -= 1
                if depth == 0: break
        else: continue
        if 'SEC(".maps")' in t[j + 1: j + 40]: continue
        if name in STRUCTS: continue
        STRUCTS[name] = {"file": rel(p), "line": lineno(t, m.start()),
                         "doc": doc_before(t, m.start()),
                         "fields": parse_struct_body(t[i + 1: j])}
    for m in re.finditer(r"\benum\s+([A-Za-z_][A-Za-z_0-9]*)\s*\{([^}]*)\}", t, re.S):
        if m.group(1) in ENUMS: continue
        vals = []
        for item in m.group(2).split(","):
            note = " ".join(x.strip() for pair in
                            re.findall(r"/\*(.*?)\*/|//([^\n]*)", item, re.S)
                            for x in pair if x)
            c = re.sub(r"\s+", " ", strip_comments(item)).strip()
            mm = re.match(r"([A-Za-z_][A-Za-z_0-9]*)\s*(?:=\s*(.+))?$", c)
            if mm: vals.append({"name": mm.group(1), "value": (mm.group(2) or "").strip(),
                                "note": re.sub(r"\s+", " ", note).strip()})
        ENUMS[m.group(1)] = {"file": rel(p), "line": lineno(t, m.start()),
                             "doc": doc_before(t, m.start()), "values": vals}

# ------------------------------------------------------------ #if/#endif map
def directives(text):
    out = []
    for m in re.finditer(r"^[ \t]*#[ \t]*(ifdef|ifndef|if|elif|else|endif|define)\b"
                         r"((?:[^\n\\]|\\\n|\\)*)", text, re.M):
        out.append((m.start(), m.end(), m.group(1),
                    re.sub(r"\s+", " ", m.group(2).replace("\\\n", " ")).strip()))
    return out
DIRS = {p: directives(TEXT[p]) for p in headers + sources}

def guards_at(dd, pos):
    stack = []
    for at, _e, kind, expr in dd:
        if at > pos: break
        if kind == "ifdef":    stack.append(expr.split()[0] if expr else "")
        elif kind == "ifndef": stack.append("!" + (expr.split()[0] if expr else ""))
        elif kind == "if":
            g = re.findall(r"defined\s*\(?\s*([A-Za-z_][A-Za-z_0-9]*)", expr)
            stack.append(g[0] if len(g) == 1 and "!" not in expr else "")
        elif kind in ("elif", "else"):
            if stack: stack[-1] = ""
        elif kind == "endif":
            if stack: stack.pop()
        else:
            continue
    return [g for g in stack if g and g.startswith("KESTREL_")]

# ------------------------------------------------------------ map templates
ATTRS = {"type": r"__uint\(\s*type\s*,\s*([A-Za-z_0-9]+)\s*\)",
         "max_entries": r"__uint\(\s*max_entries\s*,\s*([^)]+)\)",
         "map_flags": r"__uint\(\s*map_flags\s*,\s*([^)]+)\)",
         "pinning": r"__uint\(\s*pinning\s*,\s*([^)]+)\)",
         "key_size": r"__uint\(\s*key_size\s*,\s*([^)]+)\)",
         "value_size": r"__uint\(\s*value_size\s*,\s*([^)]+)\)",
         "key": r"__type\(\s*key\s*,\s*([^)]+)\)",
         "value": r"__type\(\s*value\s*,\s*([^)]+)\)",
         "values": r"__array\(\s*values\s*,\s*([^)]+)\)"}

def parse_attrs(body):
    out = {}
    for k, rx in ATTRS.items():
        m = re.search(rx, body)
        if m: out[k] = re.sub(r"[\s\\]+", " ", m.group(1)).strip()
    return out

MAPDECL = re.compile(
    r"struct\s*\{(?P<body>.*?)\}\s*(?P<name>[A-Za-z_][A-Za-z_0-9#]*)\s*SEC\(\"\.maps\"\)\s*;?",
    re.S)

RAW = []
for p in headers + sources:
    t = TEXT[p]
    for m in MAPDECL.finditer(t):
        RAW.append({"decl": m.group("name"), "file": rel(p), "abs": p,
                    "line": lineno(t, m.start()),
                    "attrs": parse_attrs(strip_comments(m.group("body"))),
                    "doc": doc_before(t, m.start()),
                    "gates": guards_at(DIRS[p], m.start())})

TEMPLATES = {d["decl"]: d for d in RAW if "##" in d["decl"] or d["decl"] == "name"}
LITERALS  = [d for d in RAW if d["decl"] not in TEMPLATES]

# which macro owns which template declaration
MACRO_OF_TEMPLATE = {}
def macro_bodies():
    out = {}
    for p in headers:
        t = TEXT[p]
        for m in re.finditer(r"^#define\s+([A-Z][A-Z_0-9]+)\(([^)]*)\)", t, re.M):
            i = m.end(); body = []
            for ln in t[i:].split("\n"):
                body.append(ln)
                if not ln.rstrip().endswith("\\"): break
            out[m.group(1)] = {"params": [x.strip() for x in m.group(2).split(",")],
                               "body": "\n".join(body), "file": rel(p),
                               "line": lineno(t, m.start())}
    return out
MACROS = macro_bodies()
for mname, mm in MACROS.items():
    for d in MAPDECL.finditer(mm["body"]):
        MACRO_OF_TEMPLATE[d.group("name")] = mname

# ------------------------------------------------------- per-program sources
DOMAIN = {"bpf": "core", "actionable": "actionable", "telemetry": "telemetry"}
INCRE  = re.compile(r'^[ \t]*#[ \t]*include[ \t]*"([^"]+)"', re.M)

def resolve_include(name):
    if name in BYREL: return BYREL[name]
    b = os.path.basename(name)
    return BYNAME.get(b)

PROGS = []
for p in sources:
    t, c = TEXT[p], CODE[p]
    d = os.path.basename(os.path.dirname(p))
    domain = DOMAIN.get(d, "core")
    stem = os.path.basename(p)[:-2]
    # includes, transitively
    seen, queue = set(), [p]
    while queue:
        f = queue.pop()
        for inc in INCRE.findall(TEXT[f]):
            r = resolve_include(inc)
            if r and r not in seen:
                seen.add(r); queue.append(r)
    # gates
    gates = set(re.findall(r"^[ \t]*#[ \t]*define[ \t]+(KESTREL_[A-Z_0-9]+)", t, re.M))
    # macro instantiations
    insts = [(m.group(1), [a.strip() for a in m.group(2).split(",")])
             for m in re.finditer(r"^([A-Z][A-Z_0-9]+)\(([^)]*)\)", t, re.M)
             if m.group(1) not in ("SEC",)]
    base = None
    for mac, args in insts:
        if mac in ("KESTREL_DEFINE_CTL", "KESTREL_DEFINE_DROPS", "KESTREL_DEFINE_LANE_RESERVE"):
            base = args[0]; break
    # SEC() attach points
    secs = []
    for m in re.finditer(r'SEC\("([^"]+)"\)\s*(?:\n|\r\n)?\s*([^\n{;]*)', t):
        s = m.group(1)
        if s in (".maps", "license", "version"): continue
        sig = re.sub(r"\s+", " ", m.group(2)).strip()
        fn = re.search(r"([A-Za-z_][A-Za-z_0-9]*)\s*\(", sig)
        secs.append({"sec": s, "fn": fn.group(1) if fn else ""})
    PROGS.append({"file": rel(p), "abs": p, "domain": domain, "stem": stem,
                  "base": base or stem, "includes": sorted(rel(x) for x in seen),
                  "inc_abs": seen, "gates": sorted(gates), "insts": insts,
                  "secs": secs,
                  "doc": clean_prose(re.sub(r"^//\s?", "",
                        "\n".join(ln[2:].lstrip() if ln.startswith("//") else ""
                                  for ln in t.split("\n")[:14] if ln.startswith("//"))))})

# program display names & rows from the composition table
ROWS = {}
pt = TEXT[os.path.join(INC, "kestrel_programs.h")]
for m in re.finditer(r"#define\s+KESTREL_ROW_([A-Z_0-9]+)\s+([^\n]+)", pt):
    cells = [x.strip() for x in m.group(2).split(",")]
    if len(cells) < 4: continue
    ROWS[cells[0]] = {"program": m.group(1), "class": cells[1],
                      "ctx": cells[2], "lane": cells[3]}

# ------------------------------------------------------- concrete map set
MAPS = {}   # key: (name, owner) -> record

def add_map(name, tmpl, owner, kind, extra=None):
    """owner: None for a shared singleton, else the program file."""
    shared = owner is None
    k = name
    rec = MAPS.get(k)
    if rec is None:
        rec = MAPS[k] = {
            "name": name, "scope": kind,
            "type": (tmpl["attrs"].get("type") or "").replace("BPF_MAP_TYPE_", ""),
            "max_entries": tmpl["attrs"].get("max_entries", ""),
            "map_flags": tmpl["attrs"].get("map_flags", ""),
            "pinned": "pinning" in tmpl["attrs"],
            "key": tmpl["attrs"].get("key", ""),
            "value": tmpl["attrs"].get("value") or tmpl["attrs"].get("values", ""),
            "key_size": tmpl["attrs"].get("key_size", ""),
            "value_size": tmpl["attrs"].get("value_size", ""),
            "decl_file": tmpl["file"], "decl_line": tmpl["line"],
            "doc": tmpl["doc"], "gates": tmpl["gates"],
            "macro": MACRO_OF_TEMPLATE.get(tmpl["decl"], ""),
            "owners": [], "producers": {}, "consumers": {}, "sites": [],
        }
        if extra: rec.update(extra)
    if owner and owner not in rec["owners"]:
        rec["owners"].append(owner)
    return rec

def subst(s, params, args):
    for p_, a in zip(params, args):
        s = re.sub(r"\b%s\b" % re.escape(p_), a, s)
    return s

# 1. maps declared literally in a program source
for pr in PROGS:
    for d in LITERALS:
        if d["abs"] == pr["abs"]:
            add_map(d["decl"], d, pr["file"], "program")

# 2. maps declared literally in a header, instantiated per including program
for d in LITERALS:
    if not d["abs"].startswith(INC): continue
    owners = [pr for pr in PROGS
              if d["abs"] in pr["inc_abs"] and all(g in pr["gates"] for g in d["gates"])]
    if not owners: continue
    if "pinning" in d["attrs"] or d["decl"] == "sockmap":
        rec = add_map(d["decl"], d, None, "shared")
        rec["owners"] = [o["file"] for o in owners]
        rec["declared_by"] = [o["file"] for o in owners]
    else:
        for o in owners:
            add_map(d["decl"], d, o["file"], "per-object")

# 3. macro-instantiated maps
def expand_macro(mac, args, depth=0):
    """Yield (macro_name, body_text_with_args_substituted) one nesting deep."""
    mm = MACROS.get(mac)
    if not mm or depth > 2: return
    body = subst(mm["body"], mm["params"], args)
    yield mac, mm, body
    for nested in re.finditer(r"^\s*(KESTREL_[A-Z_0-9]+)\(([^)]*)\)", body, re.M):
        nm = nested.group(1)
        if nm == mac or nm not in MACROS: continue
        yield from expand_macro(nm, [a.strip() for a in nested.group(2).split(",")], depth + 1)

for pr in PROGS:
    seen_inst = set()
    for mac0, args0 in pr["insts"]:
      for mac, mm, mbody in expand_macro(mac0, args0):
        if (mac, tuple(mm["params"])) in seen_inst and False: continue
        for d in MAPDECL.finditer(mbody):
            nm = d.group("name").replace("##", "")
            tmpl = {"decl": d.group("name"), "file": mm["file"], "line": mm["line"],
                    "attrs": parse_attrs(strip_comments(d.group("body"))), "gates": [],
                    "doc": doc_before(TEXT[os.path.join(ROOT, mm["file"])],
                                      TEXT[os.path.join(ROOT, mm["file"])].find("#define " + mac))}
            add_map(nm, tmpl, pr["file"], "program")
    # the four shared lane rings, from KESTREL_DEFINE_LANE in kestrel_shared_maps.h
# 4. the lane rings (macro invoked in a header, not a source)
sm = os.path.join(INC, "kestrel_shared_maps.h")
lane_mm = MACROS.get("KESTREL_DEFINE_LANE")
lane_users = [pr["file"] for pr in PROGS
              if sm in pr["inc_abs"] and "KESTREL_USE_DATA_PLANE_MAPS" in pr["gates"]]
if lane_mm:
    for m in re.finditer(r"^KESTREL_DEFINE_LANE\(([A-Za-z_0-9]+)\);", TEXT[sm], re.M):
        nm = m.group(1)
        d = list(MAPDECL.finditer(lane_mm["body"]))[-1]
        tmpl = {"decl": nm, "file": rel(sm), "line": lineno(TEXT[sm], m.start()),
                "attrs": parse_attrs(subst(strip_comments(d.group("body")),
                                           lane_mm["params"], [nm])),
                "gates": ["KESTREL_USE_DATA_PLANE_MAPS"],
                "doc": doc_before(TEXT[sm], TEXT[sm].find("#define KESTREL_DEFINE_LANE"))}
        rec = add_map(nm, tmpl, None, "shared")
        rec["owners"] = list(lane_users)
        rec["value"] = "struct %s_ring (RINGBUF)" % nm
        rec["macro"] = "KESTREL_DEFINE_LANE"

# ======================================================================
#  ACCESS ANALYSIS
# ======================================================================
# ---- map-helper vocabulary and the write-through heuristic ----------

# helper -> (role, arg index of the map)
READ  = "consume"
WRITE = "produce"
HELPERS = {
    "bpf_map_lookup_elem":        (READ,  0),
    "bpf_map_lookup_percpu_elem": (READ,  0),
    "bpf_get_local_storage":      (READ,  0),
    "bpf_for_each_map_elem":      (READ,  0),
    "bpf_ringbuf_query":          (READ,  0),
    "bpf_tail_call":              (READ,  1),
    "bpf_redirect_map":           (READ,  0),
    "bpf_sk_redirect_map":        (READ,  1),
    "bpf_msg_redirect_map":       (READ,  1),
    "bpf_sk_select_reuseport":    (READ,  1),
    "bpf_map_update_elem":        (WRITE, 0),
    "bpf_map_delete_elem":        (WRITE, 0),
    "bpf_map_push_elem":          (WRITE, 0),
    "bpf_map_pop_elem":           (WRITE, 0),
    "bpf_ringbuf_reserve":        (WRITE, 0),
    "bpf_ringbuf_output":         (WRITE, 0),
    "bpf_perf_event_output":      (WRITE, 1),
    "bpf_get_stackid":            (WRITE, 1),
    "bpf_task_storage_delete":    (WRITE, 0),
    "bpf_sk_storage_delete":      (WRITE, 0),
    "bpf_sock_map_update":        (WRITE, 1),
    "bpf_sock_hash_update":       (WRITE, 1),
    "bpf_timer_init":             (WRITE, 1),
    # get-or-create: role decided from the flags argument
    "bpf_task_storage_get":       ("storage", 0),
    "bpf_sk_storage_get":         ("storage", 0),
    "bpf_cgrp_storage_get":       ("storage", 0),
    "bpf_inode_storage_get":      ("storage", 0),
}
CALL = re.compile(r"\b(bpf_[a-z_0-9]+|kestrel_help_[a-z_0-9]+)\s*\(")

def split_args(s, start):
    """args of a call whose '(' is at start-1; returns (list, end)."""
    depth, i, cur, out = 1, start, [], []
    while i < len(s) and depth:
        ch = s[i]
        if ch in "([": depth += 1
        elif ch in ")]":
            depth -= 1
            if depth == 0: break
        if depth == 1 and ch == ",":
            out.append("".join(cur).strip()); cur = []
        else:
            cur.append(ch)
        i += 1
    out.append("".join(cur).strip())
    return out, i

# callees whose first argument is an OUT parameter: passing the looked-up
# pointer (or a member of it) to one of these is a write through the map.
OUT_PARAM = (r"(?:__builtin_mem(?:set|cpy|move)|bpf_probe_read\w*|bpf_core_read\w*|"
             r"bpf_skb_load_bytes\w*|bpf_get_current_comm|bpf_d_path|bpf_get_func_arg\w*|"
             r"bpf_sysctl_get_\w+|bpf_snprintf\w*|bpf_ringbuf_(?:reserve|output|submit|discard)|"
             r"bpf_map_(?:update|delete)_elem|bpf_perf_event_read_value|bpf_get_stack\w*|"
             r"kestrel_help_(?:probe_read\w*|skb_load_bytes|get_current_comm|sysctl_get_\w+))")

def mutates(body, var):
    """Does the body write through `var`, the pointer a lookup returned?"""
    v = re.escape(var)
    member = rf"{v}\s*(?:->|\.)\s*\w+(?:\s*\[[^\]]*\])?(?:\s*(?:->|\.)\s*\w+(?:\s*\[[^\]]*\])?)*"
    pats = [
        rf"\*\s*{v}\s*(?:\+\+|--|[-+*/|&^%]?=(?!=))",
        rf"(?<![\w.>]){member}\s*(?:\+\+|--|[-+*/|&^%]?=(?!=))",
        rf"(?:\+\+|--)\s*\*?\s*(?:{member}|{v})\b",
        rf"__sync_fetch_and_\w+\s*\(\s*&\s*(?:{member}|{v})\s*[,)]",
        rf"{OUT_PARAM}\s*\(\s*&?\s*(?:{member}|{v})\s*[,)\[]",
    ]
    return any(re.search(p, body) for p in pats)

def scan_calls(body):
    """Yield (helper, args, pos) for every map helper call in `body`."""
    for m in CALL.finditer(body):
        name = m.group(1)
        args, end = split_args(body, m.end())
        yield name, args, m.start()

ALLGATES = set()
for pr in PROGS: ALLGATES |= set(pr["gates"])

# every function-like macro, as a pseudo-function: a call written inside a
# macro body (KESTREL_DP_PROLOGUE_FOLD -> dp_ctl, dp_reserve) still reaches.
MACRO_FUNCS = {}
for p in headers + sources:
    t = TEXT[p]
    for m in re.finditer(r"^#define\s+([A-Za-z_]\w*)\(([^)]*)\)", t, re.M):
        i = m.end(); body = []
        for ln in t[i:].split("\n"):
            body.append(ln)
            if not ln.rstrip().endswith("\\"): break
        MACRO_FUNCS.setdefault(m.group(1), []).append(
            (rel(p), strip_comments("\n".join(body).replace("\\\n", "\n"))))

SAFE = re.compile(r"^[0-9()!&|<>=+\-*/% ]*$")

def _eval(expr, defs, known):
    """Evaluate a #if expression. Returns True / False / None (undecidable)."""
    e = expr
    e = re.sub(r"defined\s*\(\s*([A-Za-z_]\w*)\s*\)", lambda m: _d(m.group(1), defs, known), e)
    e = re.sub(r"defined\s+([A-Za-z_]\w*)", lambda m: _d(m.group(1), defs, known), e)
    for _ in range(4):
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b",
                    lambda m: defs.get(m.group(1), m.group(1)), e)
        if e2 == e: break
        e = e2
    e = e.replace("&&", " and ").replace("||", " or ").replace("!=", " __NE__ ")
    e = re.sub(r"!", " not ", e).replace("__NE__", "!=")
    if re.search(r"[A-Za-z_]", e.replace(" and ", " ").replace(" or ", " ").replace(" not ", " ")):
        return None
    try:
        return bool(eval(e, {"__builtins__": {}}, {}))
    except Exception:
        return None

def _d(sym, defs, known):
    if sym in defs: return "1"
    if sym in known: return "0"
    if sym.startswith(("KESTREL_", "TELEMETRY_")): return "0"
    return sym            # undecidable -> leaves an identifier behind

def filter_by_gates(text, dd, gates, defs=None):
    """Blank the regions of `text` this program's defines exclude."""
    out = list(text)
    if defs is None: defs = {g: "1" for g in gates}
    known = set(ALLGATES)
    stack = []            # {state: True/False/None, done: bool, start: int}
    def blank(a, b):
        for i in range(a, min(b, len(out))):
            if out[i] != "\n": out[i] = " "
    for at, end, kind, expr in dd:
        if kind == "define":
            if stack and any(f["state"] is False for f in stack): continue
            m = re.match(r"([A-Za-z_]\w*)\s*(?:\(|$|\s)(.*)", expr)
            if m and "(" not in expr[:len(m.group(1)) + 1] and not m.group(1).endswith("_H"):
                val = m.group(2).strip()
                if val == "": defs[m.group(1)] = "1"
                elif SAFE.match(val): defs[m.group(1)] = "(" + val + ")"
                known.add(m.group(1))
            continue
        if kind in ("ifdef", "ifndef", "if"):
            if kind == "ifdef":   v = _eval("defined(%s)" % (expr.split() or [""])[0], defs, known)
            elif kind == "ifndef": v = _eval("!defined(%s)" % (expr.split() or [""])[0], defs, known)
            else:                  v = _eval(expr, defs, known)
            stack.append({"state": v, "done": v is True, "start": end})
            continue
        if not stack: continue
        fr = stack[-1]
        if fr["state"] is False:
            blank(fr["start"], at)
        if kind == "elif":
            v = None if fr["done"] else _eval(expr, defs, known)
            if fr["done"]: v = False
            fr["state"] = v
            fr["done"] = fr["done"] or (v is True)
            fr["start"] = end
        elif kind == "else":
            fr["state"] = False if fr["done"] else (None if fr["state"] is None else True)
            fr["start"] = end
        elif kind == "endif":
            stack.pop()
    return "".join(out)

KW_NOT_FN = {"if","for","while","switch","return","sizeof","do","else","case",
             "defined","__builtin_expect","typeof","_Static_assert"}

def functions_in(text):
    """name -> [body], for every function definition in `text`."""
    out = {}
    for m in re.finditer(r"\)\s*\{", text):
        # walk back to the matching '('
        j = m.start(); depth = 0; i = j
        while i >= 0:
            if text[i] == ")": depth += 1
            elif text[i] == "(":
                depth -= 1
                if depth == 0: break
            i -= 1
        if i < 0: continue
        k = i - 1
        while k >= 0 and text[k] in " \t\n\\": k -= 1
        e = k + 1
        while k >= 0 and (text[k].isalnum() or text[k] == "_"): k -= 1
        name = text[k + 1:e]
        if not name or name in KW_NOT_FN or name[0].isdigit(): continue
        # something must precede the name on the declaration (a return type)
        q = k
        while q >= 0 and text[q] in " \t\n\\*": q -= 1
        if q < 0 or not (text[q].isalnum() or text[q] in "_>"): continue
        if text[q] == ">" or (q > 0 and text[q - 1] == "."): continue
        o = m.end() - 1; depth = 0; jj = -1
        for t_ in range(o, len(text)):
            if text[t_] == "{": depth += 1
            elif text[t_] == "}":
                depth -= 1
                if depth == 0: jj = t_; break
        flat = text.find("\n}", o)
        if jj < 0 or (flat >= 0 and jj > flat + 1): jj = flat + 1
        if jj <= o: continue
        out.setdefault(name, []).append((text[o + 1: jj], k + 1))
    return out

IDENT = re.compile(r"\b([A-Za-z_]\w*)\s*\(")

def analyse(pr):
    """Returns {map_name: {'roles': set, 'sites': [...]}} for one program."""
    gates = set(pr["gates"])
    files = [pr["abs"]] + sorted(pr["inc_abs"])
    defs = {g: "1" for g in gates}
    for _pass in (0, 1):
        units = []
        for f in files:
            units.append((rel(f), filter_by_gates(CODE[f], DIRS[f], gates, defs)))
    own = units[0][1]
    # macro instantiations, substituted
    for mac, args in pr["insts"]:
        mm = MACROS.get(mac)
        if not mm: continue
        body = mm["body"].replace("\\\n", "\n")
        body = subst(strip_comments(body), mm["params"], args).replace("##", "")
        units.append((mm["file"] + " :: " + mac + "(" + args[0] + ")", body))

    funcs, roots = {}, set()
    for label, txt in units:
        for nm, bodies in functions_in(txt).items():
            for b, at in bodies:
                funcs.setdefault(nm, []).append((label, b))
                head = txt[max(0, at - 400):at]
                k = head.rfind("SEC(")
                if k >= 0:
                    tail = head[k:]
                    if ('SEC(".maps")' not in tail and 'SEC("license")' not in tail
                            and tail.count("{") == 0 and tail.count(";") == 0):
                        roots.add(nm)

    for sd in pr["secs"]:
        if sd["fn"]: roots.add(sd["fn"])
    # BPF_PROG()/BPF_KPROBE() wrappers name the function in the macro args
    for m in re.finditer(r"BPF_(?:PROG|KPROBE|KRETPROBE|KSYSCALL)\s*\(\s*([A-Za-z_]\w*)", own):
        roots.add(m.group(1))
    # timer callbacks are reached from bpf_timer_set_callback()
    for _l, txt in units:
        for m in re.finditer(r"bpf_timer_set_callback\s*\([^,]+,\s*([A-Za-z_]\w*)", txt):
            roots.add(m.group(1))
    for mac, args in pr["insts"]:
        for a in args:
            if re.fullmatch(r"[a-z_]\w*", a): roots.add(a)
    for nm, defs_ in MACRO_FUNCS.items():
        for label, body in defs_:
            funcs.setdefault(nm, []).append((label + " (macro)", body))
    roots &= set(funcs)
    reach, queue = set(roots), list(roots)
    while queue:
        fn = queue.pop()
        for label, body in funcs.get(fn, []):
            for m in IDENT.finditer(body):
                nm = m.group(1)
                if nm in funcs and nm not in reach:
                    reach.add(nm); queue.append(nm)
            # token-pasted macro calls (KESTREL_FV_CAST_##cast(...)) hide the
            # callee behind ##, so any known UPPERCASE macro named in the body
            # counts as reached.
            for m in re.finditer(r"\b(\w{3,})\b", body):
                nm = m.group(1)
                if nm in funcs and nm not in reach:
                    reach.add(nm); queue.append(nm)

    hits = {}
    def note(mapname, role, site):
        e = hits.setdefault(mapname, {"roles": set(), "sites": []})
        e["roles"].add(role)
        if site not in e["sites"]: e["sites"].append(site)

    for fn in sorted(reach):
        for label, body in funcs.get(fn, []):
            for helper, args, pos in scan_calls(body):
                spec = HELPERS.get(helper)
                if not spec:
                    spec = HELPERS.get(helper.replace("kestrel_help_", "bpf_"))
                if not spec: continue
                role, idx = spec
                if idx >= len(args): continue
                a = args[idx].strip()
                m = re.match(r"&\s*([A-Za-z_]\w*)$", a)
                if not m: continue
                mapname = m.group(1)
                if role == "storage":
                    flags = args[3] if len(args) > 3 else ""
                    r = WRITE if "F_CREATE" in flags else READ
                    note(mapname, r, {"fn": fn, "file": label, "helper": helper})
                    if r == WRITE:
                        note(mapname, READ, {"fn": fn, "file": label, "helper": helper})
                    continue
                note(mapname, role, {"fn": fn, "file": label, "helper": helper})
                if helper.endswith("lookup_elem") or helper.endswith("lookup_percpu_elem"):
                    before = body[:pos].replace("\n", " ")
                    mm = re.search(r"(?:^|[;{}()=])\s*([A-Za-z_][\w \t*]*?\b)?(\w+)\s*=\s*$", before)
                    if not mm: continue
                    decl, var = (mm.group(1) or ""), mm.group(2)
                    if not decl:   # assigned to a variable declared earlier
                        dm = re.search(r"\b((?:const\s+)?[\w]+(?:\s+\w+)*\s*\**)\s*%s\s*[;,=]"
                                       % re.escape(var), body)
                        decl = dm.group(1) if dm else ""
                    if "const" in decl: continue
                    tail = body[pos:]
                    if mutates(tail, var):
                        note(mapname, WRITE,
                             {"fn": fn, "file": label, "helper": "lookup + write-through"})
                    elif re.search(r"return\s*(?:\([^)]*\)\s*)?%s\s*;" % re.escape(var), tail):
                        note(mapname, WRITE,
                             {"fn": fn, "file": label,
                              "helper": "lookup returned as a writable pointer"})
    writes_ring = any("bpf_ringbuf_reserve(" in b or "bpf_ringbuf_output(" in b
                      for fn in reach for _l, b in funcs.get(fn, []))
    if writes_ring:
        for mapname, e in hits.items():
            rec = MAPS.get(mapname)
            if rec and rec["type"] == "ARRAY_OF_MAPS":
                e["roles"].add(WRITE)
                e["sites"].append({"fn": "dp_reserve", "file": "include/kestrel_data_plane.h",
                                   "helper": "bpf_ringbuf_reserve on the looked-up ring"})
    return hits, reach, funcs

PROG_MAPS = {}
for pr in PROGS:
    hits, reach, funcs = analyse(pr)
    pr["reach"] = sorted(reach)
    PROG_MAPS[pr["file"]] = hits

# attach edges to the map records
for pr in PROGS:
    for mapname, e in PROG_MAPS[pr["file"]].items():
        rec = MAPS.get(mapname)
        if rec is None: continue
        if rec["scope"] != "shared" and pr["file"] not in rec["owners"]:
            continue
        for role in e["roles"]:
            bucket = "producers" if role == WRITE else "consumers"
            rec[bucket].setdefault(pr["file"], [])
            for s in e["sites"]:
                if s not in rec[bucket][pr["file"]]:
                    rec[bucket][pr["file"]].append(s)

# ======================================================================
#  EMIT
# ======================================================================
PROG_TYPE_RE = re.compile(r"^BPF_PROG_TYPE_([A-Z_0-9]+)$")

FAMILY = [
    (r"_dr$",       "Drop counters",     "Per-cause drop tally; the program's own honesty ledger."),
    (r"_ct$",       "Control block",     "One slot the userspace controller writes and the program reads once per event."),
    (r"_fl$",       "Filter predicates", "The compiled predicate block the in-kernel filter evaluates."),
    (r"_tb$",       "Sample bucket",     "Per-CPU token bucket for the sampling gate."),
    (r"_ag$",       "Aggregate",         "Per-key fold under AGGREGATE mode, drained by userspace."),
    (r"_s\d$",      "Side table",        "Per-file data written once per LRU residency and joined at export."),
    (r"_pp$",       "Policy path ids",   "The AUTHORED prefix id for a file, cached per (dev, ino, tag)."),
    (r"_ps$",       "Probe scratch",     "Per-CPU scratch the policy probe claims for one event."),
    (r"_cfg$",      "Program config",    "The rule set this actionable program enforces."),
    (r"^kestrel_lane_", "Event lane",    "One ARRAY_OF_MAPS per lane; each slot is a per-CPU ring the records go out on."),
    (r"_ev$",       "Record ring",       "The telemetry record stream for this metric."),
    (r"_stats$",    "Live counters",     "The metric's running counters."),
    (r"_shadow$|_shad$", "Shadow counters", "Each counter at the last emit, so a delta is a subtraction."),
    (r"_meta$",     "Stream metadata",   "Schema and interval metadata for the record stream."),
    (r"_timers$",   "Flush timers",      "One bpf_timer per CPU driving the periodic flush."),
    (r"_emit$",     "Emit state",        "Sequence and drop state for the record stream."),
    (r"_hist|hist$", "Histogram",        "Latency or errno histogram buckets."),
    (r"scrat|scratch$", "Scratch",       "Per-CPU scratch buffer; holds nothing between events."),
]
NAMED = {
  "kestrel_task":       ("Task slot",        "The per-task correlation, identity and chain state every task-context program shares."),
  "kestrel_sock":       ("Socket slot",      "Per-socket owner, counters and class, hung off the socket and freed with it."),
  "kestrel_lineage":    ("Lineage seed",     "What a fork hook leaves for the child, taken and deleted by the child's first event."),
  "kestrel_vocab":      ("Vocabulary",       "Interned program and comm strings, keyed by hash; 0 means not in the vocabulary."),
  "kestrel_verdicts":   ("Verdict cache",    "The classifier's published verdicts, keyed by the record signature."),
  "kestrel_ports":      ("Port gate",        "The ports the verdict cache is allowed to answer for."),
  "kestrel_path_class": ("Path classes",     "Longest-prefix classification of a path."),
  "kestrel_policy_path":("Policy prefixes",  "The AUTHORED prefix trie the policy path id comes from."),
  "kestrel_addr_class": ("Address classes",  "Longest-prefix classification of a peer address."),
  "kestrel_block":      ("Block list",       "Entries the response path writes and the enforcers read."),
  "kestrel_templates":  ("Chain templates",  "The compiled corpus chains the template matcher walks."),
  "kestrel_template_index": ("Template index", "Which template nodes an emitter can start."),
  "kestrel_tree":       ("Fitted tree",      "The decision tree the verdict backend evaluates."),
  "kestrel_fv_spec":    ("Feature spec",     "The feature-vector layout, published for userspace."),
  "kestrel_fvsc":       ("Feature scratch",  "Per-CPU feature vector, built per event."),
  "kestrel_baseline":   ("Baseline",         "The per-syscall thresholds the accumulator compares against."),
  "kestrel_host":       ("Host state",       "This host's drift word, written by userspace."),
  "kestrel_attach":     ("Attach ordinal",   "Per-cgroup attach ordinal, so one program can tell its attach points apart."),
  "kestrel_policy_meta":("Policy metadata",  "Generation and layout of the policy the program reads."),
  "kestrel_policy_args":("Argument needles", "Hashed AUTHORED argument needles."),
  "kestrel_argw":       ("Argument walk",    "Per-CPU scratch for the argument walk."),
  "kestrel_policy_witness": ("Policy witness", "Per-CPU witness counters for the policy probe."),
  "kestrel_l7sc":       ("L7 scratch",       "Per-CPU scratch for the L7 classifier."),
  "kestrel_pathc":      ("Path walk buffer", "Per-CPU dentry-walk chain and path buffer."),
  "sockmap":            ("Sockmap",          "The grandfathered socket map; not pinned by name."),
}
def family_of(name, macro):
    if name in NAMED: return NAMED[name]
    for rx, label, blurb in FAMILY:
        if re.search(rx, name): return label, blurb
    return "State", ""

def flow_of(rec):
    p, c = bool(rec["producers"]), bool(rec["consumers"])
    if p and c:  return "kernel-state"
    if p:        return "kernel-output"
    if c:        return "control-input"
    return "declared-only"

FLOW_LABEL = {
    "kernel-state":  "Written and read in kernel",
    "kernel-output": "Written in kernel, drained by userspace",
    "control-input": "Written by userspace, read in kernel",
    "declared-only": "Declared, no reachable in-kernel access",
}

# ---------------------------------------------------------------- prose
# The docs on these pages are the sources' own comments, quoted. A comment
# that names a source file is naming something the pages do not show, so the
# mention is rewritten: a file that IS a program becomes that program's name
# (the unit the pages are written in), anything else is dropped along with
# the preposition that introduced it, so the sentence still parses. Research
# notes (*.md) are citations, not source paths, and stay.
FILE_RE    = r"[\w][\w/.-]*\.(?:c|h|rs|py)"
FILE_TOKEN = re.compile(r"(?<![\w/.-])(" + FILE_RE + r")('s)?(?![\w/-])(?!\.\w)")
PROSE_PROG = {}

def _prose_program_names():
    """basename of a program's source, and of its header -> the program name."""
    out = {}
    for pr in PROGS:
        stem = pr["stem"]
        m = PROG_TYPE_RE.match(stem)
        nm = m.group(1) if m else stem.upper()
        out[os.path.basename(pr["file"])] = nm
        out[stem + ".h"] = nm
    return out

def clean_prose_files(text):
    """Rewrite a quoted comment so it names no source file.

    A file that IS a program becomes that program's name -- the unit these
    pages are written in. Anything else is removed along with whatever
    introduced it (a list separator, the preposition, or the parenthetical it
    sat in) so the sentence still parses. Nothing is touched unless a file
    name was actually found: `dp_count()` keeps its parentheses."""
    if not text or "." not in text:
        return text

    def swap(m):
        nm = PROSE_PROG.get(os.path.basename(m.group(1)))
        return (nm + (m.group(2) or "")) if nm else "\x00"

    out = FILE_TOKEN.sub(swap, text)
    if "\x00" not in out:
        return out

    # A parenthetical that OPENS with a removal was an aside ABOUT that file
    # -- "(tests/guards.rs holds that rule)" has no subject left -- so the
    # whole aside goes. This also covers a parenthetical that was nothing but
    # file names.
    out = re.sub(r"\s*\(\s*\x00[^()]*\)", "", out)
    # A removal in running prose takes the preposition that introduced it.
    # This runs BEFORE the separator rules: "by <file>, and" has to lose the
    # "by", and a comma-first rule would consume the marker they match on.
    out = re.sub(r"\s+(?:in|by|from|at|to|of|under|with|via|than|inside|on|and)\s+\x00",
                 "", out, flags=re.IGNORECASE)
    # Otherwise a removal takes whichever list separator attached it.
    out = re.sub(r"\s*[,;]\s*\x00", "", out)
    out = re.sub(r"\x00\s*[,;]\s*", "", out)
    out = out.replace("\x00", "")
    out = re.sub(r"\(\s+", "(", out)
    out = re.sub(r"\s+([,.;:)])", r"\1", out)
    out = re.sub(r"\s{2,}", " ", out)
    return out.strip()

# ---- programs ----------------------------------------------------------
PROSE_PROG.update(_prose_program_names())

prog_out, prog_index = [], {}
for pr in PROGS:
    stem = pr["stem"]
    m = PROG_TYPE_RE.match(stem)
    if m:
        ptype = "BPF_PROG_TYPE_" + m.group(1)
        title = m.group(1)
    else:
        ptype = ""
        title = stem.upper()
    row = ROWS.get(pr["base"], {})
    secs = sorted({s["sec"] for s in pr["secs"] if s["sec"]})
    prog_index[pr["file"]] = len(prog_out)
    prog_out.append({
        "id": len(prog_out), "file": pr["file"], "base": pr["base"],
        "name": title, "prog_type": ptype, "domain": pr["domain"],
        "class": row.get("class", ""), "ctx": row.get("ctx", ""),
        "lane": row.get("lane", ""),
        "attach": secs, "attach_count": len(pr["secs"]),
        "gates": [g for g in pr["gates"] if g.startswith(("KESTREL_USE_", "KESTREL_HELPER_",
                                                          "KESTREL_PATH", "KESTREL_REACT",
                                                          "KESTREL_POLICY", "KESTREL_TREE"))],
        "doc": clean_prose_files(pr["doc"])[:600],
        "produces": [], "consumes": [],
    })

# ======================================================================
#  EXAMPLES — a worked value for every key and value member
#
#  The example literals are ILLUSTRATIVE: constructed to show the encoding,
#  not captured from a run. What they decode TO is not invented -- bit names,
#  enum names and their values are read out of the headers, so an example
#  either decodes against real constants or says only what the C type says.
#  `basis` records which of those it was, and the About panel repeats it.
# ======================================================================
_INT   = re.compile(r"^\(?\s*(?:(0x[0-9a-fA-F]+)|(\d+))\s*[uUlL]*\s*\)?$")
_SHIFT = re.compile(r"^\(?\s*1\s*[uUlL]*\s*<<\s*\(?\s*(\d+)\s*\)?\s*\)?$")

# Family roots, longest first: KESTREL_E_EXEC belongs to KESTREL_E_, not to a
# prefix guessed from its own last underscore.
FAMILY_ROOTS = [
    "KESTREL_HOOK_TRACEPOINT_IO_URING_", "KESTREL_HOOK_TRACEPOINT_",
    "KESTREL_HOOK_LSM_", "KESTREL_VERDICT_SOURCE_", "KESTREL_BLOCK_REFUSE_",
    "KESTREL_BLOCK_ORIGIN_", "KESTREL_ERRNO_CLASS_", "KESTREL_SOCK_FLAG_",
    "KESTREL_CORR_VALID_", "KESTREL_L7_HAS_TLS_", "KESTREL_L7_IPPROTO_",
    "KESTREL_L7_HAS_", "KESTREL_SIG_PROP_", "KESTREL_AUX_HAS_",
    "KESTREL_NF_IPPROTO_", "KESTREL_LWT_IPPROTO_", "KESTREL_LWT_ETH_P_",
    "KESTREL_IPPROTO_", "KESTREL_ETH_P_", "KESTREL_PATH_F_", "KESTREL_FV_SRC_",
    "KESTREL_TEMPLATE_", "KESTREL_REACTION_", "KESTREL_WINDOW_", "KESTREL_PIVOT_",
    "KESTREL_DRIFT_", "KESTREL_PRED_", "KESTREL_MODE_", "KESTREL_ADDR_",
    "KESTREL_PATH_", "KESTREL_DROP_", "KESTREL_READ_", "KESTREL_TAG_",
    "KESTREL_DIR_", "KESTREL_ENV_", "KESTREL_NS_", "KESTREL_E_",
    "TELEMETRY_GUARD_", "TELEMETRY_PTRACE_", "TELEMETRY_PR_SET_", "TELEMETRY_TASK_",
]
CONSTS, FAMILIES = {}, {}
# Families whose members are indices used as a shift, not values to OR:
# KESTREL_E_BIT(e) is 1<<e, KESTREL_READ_BIT(class) is 1<<(class-1).
INDEX_FAMILY = {"KESTREL_E_": 0, "KESTREL_READ_": 1, "KESTREL_PATH_": 1}

def build_constant_tables():
    for p in headers + sources:
        for m in re.finditer(r"^#define\s+((?:KESTREL|TELEMETRY)_[A-Z0-9_]+)\s+([^\n/]+)",
                             CODE[p], re.M):
            name, raw = m.group(1), m.group(2).strip()
            v, mm = None, _INT.match(raw)
            if mm:
                v = int(mm.group(1), 16) if mm.group(1) else int(mm.group(2))
            else:
                ms = _SHIFT.match(raw)
                if ms: v = 1 << int(ms.group(1))
            if v is not None:
                CONSTS.setdefault(name, v)
    for name, v in CONSTS.items():
        for root in FAMILY_ROOTS:
            if name.startswith(root) and name != root.rstrip("_"):
                FAMILIES.setdefault(root, {})[name[len(root):]] = v
                break
    for root, vals in list(FAMILIES.items()):
        # a family whose members are all distinct powers of two is a bitmask
        nz = [v for v in vals.values() if v]
        FAMILIES[root] = {
            "values": vals,
            "bitmask": bool(nz) and all(v & (v - 1) == 0 for v in nz)
                       and len(set(nz)) == len(nz),
        }

def enum_pairs(name):
    e = ENUMS.get(name)
    if not e: return []
    out, nxt = [], 0
    for v in e["values"]:
        raw = (v.get("value") or "").strip()
        m = _INT.match(raw) if raw else None
        if m: nxt = int(m.group(1), 16) if m.group(1) else int(m.group(2))
        out.append((v["name"], nxt)); nxt += 1
    return out

# (struct, member) -> family root or "enum:<name>". The struct qualifies the
# name because `flags` means one thing on a socket slot and another on a
# record header.
FIELD_FAMILY = {
    ("kestrel_task_slot", "tags"): "KESTREL_TAG_",
    ("kestrel_task_slot", "emitter_bits"): "KESTREL_E_",
    ("kestrel_task_slot", "inherited_bits"): "KESTREL_E_",
    ("kestrel_task_slot", "read_bits"): "KESTREL_READ_",
    ("kestrel_task_slot", "errno_mask"): "KESTREL_ERRNO_CLASS_",
    ("kestrel_task_slot", "last_path_class"): "KESTREL_PATH_",
    ("kestrel_task_corr", "valid"): "KESTREL_CORR_VALID_",
    ("kestrel_sock_slot", "flags"): "KESTREL_SOCK_FLAG_",
    ("kestrel_sock_slot", "emitter_bits"): "KESTREL_E_",
    ("kestrel_sock_slot", "peer_class"): "KESTREL_ADDR_",
    ("kestrel_sock_slot", "owner_read_bits"): "KESTREL_READ_",
    ("kestrel_lineage_seed", "tags"): "KESTREL_TAG_",
    ("kestrel_lineage_seed", "inherited_bits"): "KESTREL_E_",
    ("kestrel_ctl", "mode_flags"): "KESTREL_MODE_",
    ("kestrel_ctl", "lane"): "enum:kestrel_lane",
    ("kestrel_ctl", "reaction_ceiling"): "enum:kestrel_reaction_class",
    ("kestrel_block_key", "kind"): "enum:kestrel_block_kind",
    ("kestrel_block_entry", "reaction_class"): "enum:kestrel_reaction_class",
    ("kestrel_path_value", "flags"): "KESTREL_PATH_F_",
    ("kestrel_path_value", "path_class"): "KESTREL_PATH_",
    ("kestrel_host_state", "drift_bits"): "KESTREL_DRIFT_",
    ("kestrel_policy_aux", "flags"): "KESTREL_AUX_HAS_",
    ("kestrel_envelope", "flags"): "KESTREL_ENV_",
    ("kestrel_envelope", "lane"): "enum:kestrel_lane",
    ("kestrel_pred", "op"): "KESTREL_PRED_",
    ("kestrel_template", "window"): "KESTREL_WINDOW_",
    ("kestrel_template", "pivot"): "KESTREL_PIVOT_",
    ("kestrel_fv_spec", "src"): "KESTREL_FV_SRC_",
    ("kestrel_verdict", "source"): "KESTREL_VERDICT_SOURCE_",
    ("telemetry_blocking_state", "guard_bits"): "TELEMETRY_GUARD_",
    ("telemetry_blocking_stuck", "state"): "TELEMETRY_TASK_",
}
# Members the headers describe precisely enough to quote; the generic rules
# below would say something true but thinner.
OVERRIDE = {
  ("kestrel_task_slot","program_id"): ("4812",
    "A kestrel_vocab id for the exec target's basename. 0 means the name is not in the vocabulary, which is the classifier's own gate."),
  ("kestrel_task_slot","comm_id"): ("911",
    "A kestrel_vocab id for comm. Re-interned by TRACEPOINT at prctl(PR_SET_NAME)."),
  ("kestrel_task_slot","arg_bits"): ("0x00000005",
    "One bit per AUTHORED argv needle this command line matched (kestrel_policy_args). 0 on a host whose collector wrote no needles."),
  ("kestrel_task_slot","write_dests"): ("2",
    "Distinct write-mode destinations this incarnation. Saturates at 255. The corpus reads it as 0, or >= 1; the exact count past that is not used."),
  ("kestrel_task_slot","open_fanout"): ("37",
    "Distinct inodes opened for reading this incarnation, saturating at 65535. This is node 7's N."),
  ("kestrel_task_slot","fired_nodes"): ("0x0240",
    "One bit per template node 1..16 that has fired this incarnation; a chain fires once per incarnation."),
  ("kestrel_task_slot","last_inode"): ("3407875",
    "The last write destination, kept so a repeat of the same inode does not count twice."),
  ("kestrel_task_slot","last_read_inode"): ("3407875",
    "The last inode opened for reading, the one-entry dedup behind open_fanout."),
  ("kestrel_task_slot","err_run"): ("4",
    "Consecutive failing syscalls, saturating at 255: a wrap to 0 would read as 'it just succeeded'."),
  ("kestrel_task_slot","slow_run"): ("0",
    "Consecutive syscalls over the baseline's latency threshold, saturating at 255."),
  ("kestrel_task_corr","nsproxy"): ("0xffff9a1c0142b800",
    "The nsproxy these inode numbers came from. Never published; compared per event to catch setns() and unshare()."),
  ("kestrel_task_corr","ns_pid"): ("1",
    "The pid as its own pid namespace numbers it, which is 1 for a container's init."),
  ("kestrel_task_slot","read_bits"): ("0x05",
    "KESTREL_READ_BIT(class) per credential class this incarnation read: bit (class - 1), so SHADOW is bit 0 and KEYRING is bit 2. Set by LSM file_open only."),
  ("kestrel_sock_slot","owner_read_bits"): ("0x05",
    "A copy of the owner task's read_bits taken at connect, because SOCK_OPS has no task slot of its own."),
  ("kestrel_task_slot","last_cookie"): ("0",
    "Declared but never written and never read -- zeroed at each new incarnation and nothing else touches it."),
  ("kestrel_task_slot","flags"): ("0",
    "Per-incarnation flags on the task slot; no bit names are defined in the headers yet."),
  ("kestrel_sock_slot","weight_acc"): ("0", "Accumulated chain weight for this socket, 16-bit."),
  ("kestrel_ctl","backends"): ("0x03",
    "bit 0 CACHE, bit 1 TREE, bit 2 TEMPLATE -- which verdict backends the controller has enabled."),
  ("kestrel_ctl","sample_shift"): ("4",
    "Emit 1 in 2^n on an empty token bucket; 0 turns the tail sampler off."),
  ("kestrel_ctl","interval_ns_shift"): ("20",
    "The token refill interval as a power of two nanoseconds: 20 is about 1 ms."),
  ("kestrel_ctl","sensor_tgid"): ("1742",
    "The collector's own process, which no response may name. 0 = none given."),
}

# a family named in the member's own comment beats the table
COMMENT_FAMILY = re.compile(r"(KESTREL_[A-Z0-9]+(?:_[A-Z0-9]+)*?_)\*|enum (kestrel_\w+)")

def const_family_of(struct, field):
    key = (struct, field["name"].split("[")[0])
    if key in FIELD_FAMILY: return FIELD_FAMILY[key]
    m = COMMENT_FAMILY.search(field.get("note") or "")
    if m:
        if m.group(2) and m.group(2) in ENUMS: return "enum:" + m.group(2)
        if m.group(1) in FAMILIES: return m.group(1)
    t = field["type"]
    m = re.match(r"(?:const\s+)?enum\s+(\w+)$", t)
    if m and m.group(1) in ENUMS: return "enum:" + m.group(1)
    return None

# ---- units and widths --------------------------------------------------
WIDTH = {"__u8": 8, "__s8": 8, "__u16": 16, "__s16": 16, "__u32": 32, "__s32": 32,
         "__u64": 64, "__s64": 64, "int": 32, "unsigned int": 32, "char": 8,
         "bool": 8, "long": 64, "unsigned long": 64}

def _art(bits):
    """'An 8-bit', 'A 32-bit' -- the article follows how the number is said."""
    return "An" if bits == 8 else "A"

def human_ns(ns):
    if ns < 1000: return f"{ns} ns"
    if ns < 1_000_000: return f"{ns/1000:.1f} µs"
    if ns < 1_000_000_000: return f"{ns/1e6:.1f} ms"
    if ns < 60_000_000_000: return f"{ns/1e9:.2f} s"
    return f"{ns/6e10:.1f} min"

def human_bytes(n):
    for u, d in (("GiB", 1 << 30), ("MiB", 1 << 20), ("KiB", 1 << 10)):
        if n >= d: return f"{n/d:.1f} {u}"
    return f"{n} B"

# Words the member names are built from, so an undocumented member still gets
# a description that follows the name rather than a shrug.
TOKENS = {
    "rx": "received", "tx": "transmitted", "sys": "syscall", "unint": "uninterruptible",
    "ns": "nanoseconds", "ts": "timestamp", "ino": "inode number", "inum": "inode number",
    "tgid": "thread-group id", "pid": "process id", "ppid": "parent process id",
    "tid": "thread id", "uid": "user id", "gid": "group id", "euid": "effective user id",
    "cgroup": "cgroup", "dev": "device", "lat": "latency", "hist": "histogram",
    "errno": "errno", "prot": "protection bits", "vma": "virtual memory area",
    "seq": "sequence number", "gen": "generation", "sum": "sum", "max": "maximum",
    "min": "minimum", "cnt": "count", "n": "count", "len": "length", "sz": "size",
    "src": "source", "dst": "destination", "addr": "address", "port": "port",
    "proto": "protocol", "iface": "interface", "if": "interface", "blk": "block",
    "acc": "accumulator", "run": "run length", "shad": "shadow", "scrat": "scratch",
}
def describe_name(name):
    parts = [p for p in re.split(r"[_\d]+", name.split("[")[0]) if p]
    words = [TOKENS.get(p, p) for p in parts]
    return " ".join(words)

def example_for(struct, f):
    """(example literal, what it decodes to, basis)."""
    name = f["name"].split("[")[0]
    arr  = re.search(r"\[([^\]]*)\]", f["name"])
    ty   = re.sub(r"^const\s+", "", f["type"]).strip()
    note = (f.get("note") or "")
    fam  = const_family_of(struct, f)

    key = (struct, name)
    if key in OVERRIDE:
        ex, dec = OVERRIDE[key]
        return ex, dec, "source"

    # a note that is nothing but a constant name IS the value
    nt = note.strip().rstrip(".")
    if re.fullmatch(r"(?:KESTREL|TELEMETRY)_[A-Z0-9_]+", nt) and nt in CONSTS:
        return str(CONSTS[nt]), f"{nt} = {CONSTS[nt]}.", "constants"

    if name.startswith(("_pad", "_rsv", "_reserved")):
        return "0", "Padding. Never written; not part of the ABI.", "type"

    if ty.startswith(("struct ", "union ")):
        inner = ty.split()[-1]
        return "", f"The members of {ty}" + (f", listed under its own entry." if inner in TYPES_SEEN else "."), "type"

    # ---- a named constant family ----------------------------------------
    if fam and fam.startswith("enum:"):
        pairs = [(n, v) for n, v in enum_pairs(fam[5:]) if not n.endswith(("_COUNT", "_MAX", "_SLOTS"))]
        if pairs:
            n, v = pairs[min(1, len(pairs) - 1)]
            rest = ", ".join(f"{v2}={n2}" for n2, v2 in pairs[:5])
            return str(v), f"{n} — one of {rest}", "constants"
    if fam and fam in FAMILIES:
        vals = {k: v for k, v in FAMILIES[fam]["values"].items()
                if not k.endswith(("MAX", "COUNT", "SLOTS", "CAP", "NONE"))}
        if vals and fam in INDEX_FAMILY and name.endswith("_bits"):
            # the constants are bit POSITIONS; the member holds 1<<position
            off = INDEX_FAMILY[fam]
            picked = sorted(vals.items(), key=lambda kv: kv[1])[:2]
            val = 0
            for _n, v in picked: val |= 1 << max(0, v - off)
            names = " | ".join(n for n, _v in picked)
            allnames = ", ".join(f"{n}=bit {v - off}" for n, v in
                                 sorted(vals.items(), key=lambda kv: kv[1])[:6])
            return (f"0x{val:04x}", f"{names}. One bit per {fam.rstrip('_')} index: {allnames}",
                    "constants")
        if vals:
            if FAMILIES[fam]["bitmask"]:
                picked = sorted(vals.items(), key=lambda kv: kv[1])[:2]
                val = 0
                for _n, v in picked: val |= v
                names = " | ".join(n for n, _v in picked)
                allnames = ", ".join(f"{fam}{n}=0x{v:x}" for n, v in
                                     sorted(vals.items(), key=lambda kv: kv[1])[:6])
                return f"0x{val:04x}", f"{names}. Bits: {allnames}", "constants"
            picked = sorted(vals.items(), key=lambda kv: kv[1])
            n, v = picked[min(1, len(picked) - 1)]
            rest = ", ".join(f"{v2}={n2}" for n2, v2 in picked[:5])
            return str(v), f"{fam}{n} — one of {rest}", "constants"

    # ---- an emitter index used as a bit position ------------------------
    if name.endswith("_stamp") or name == "order_stamp":
        return "[1,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0]", (
            "One byte per emitter: the order it first fired this incarnation, "
            "1-based, 0 for an emitter that has not fired."), "constants"

    # ---- byte arrays -----------------------------------------------------
    if arr and ty in ("__u8", "char", "unsigned char"):
        if re.search(r"path|name|comm|exe|interp|args|filename", name):
            return '"/usr/bin/curl"', f"A NUL-terminated string, at most {arr.group(1)} bytes.", "type"
        return "00 00 00 00 …", f"{arr.group(1)} raw bytes.", "type"
    if arr:
        return "[0, 0, …]", f"{arr.group(1)} × {ty}.", "type"

    bits = WIDTH.get(ty, 32)
    cap  = (1 << bits) - 1
    sat  = "saturates" in note.lower()

    # ---- units the name settles -----------------------------------------
    if name.endswith(("_ns", "_boottime")) or name in ("now", "enter_ts"):
        stamp = bool(re.search(r"boottime|_ts$|^created|^first|^last|start|enter|emit|_at$", name))
        v = 812_345_678_901 if stamp else 1_450_000
        what = ("a point in time on the boot clock" if stamp else "a duration")
        return str(v), f"{human_ns(v)} — {what}, in nanoseconds, {bits}-bit.", "unit"
    if name.endswith("_bytes") or name.startswith("bytes_") or name in ("count_bytes",):
        v = 1_048_576
        return str(v), f"{human_bytes(v)} — a byte count, {bits}-bit.", "unit"
    if name.endswith(("_ino", "_inum")):
        return "3407875", f"An inode number, {bits}-bit. Stable across rename and hardlink.", "unit"
    if name.endswith("_id") or name in ("cgroup_id", "node_id"):
        return "12406", f"An opaque {bits}-bit id; compare it, do not interpret it.", "unit"
    if name.endswith(("_hash", "cookie")) or name.startswith("hash"):
        return "0x4c968a90ace3649b", f"A {bits}-bit hash; an identity to join on, not a value to read.", "unit"
    if re.search(r"^(?:owner_)?(?:pid|tgid|ppid|tid|[eu]?uid|gid)(?:_at_exec)?$", name):
        return "1742", f"{describe_name(name).capitalize()}, {bits}-bit.", "unit"
    if name.endswith(("_port",)) or name in ("sport", "dport"):
        return "443", f"A TCP/UDP port, {bits}-bit, host byte order at this point.", "unit"
    if re.search(r"count|hits|_n$|fanout|dests|depth|entries|events|switches|errors|drops", name):
        v = 7
        extra = f" Saturates at {cap}: it is not decremented." if sat else ""
        return str(v), f"{_art(bits)} {bits}-bit counter — {describe_name(name)}.{extra}", "unit"
    if name.endswith(("_len", "_size")) or name in ("size", "len"):
        return "64", f"A length in bytes, {bits}-bit.", "unit"
    if name in ("seq", "generation") or name.endswith(("_generation", "_seq", "_version")):
        return "3", f"{_art(bits)} {bits}-bit {describe_name(name)}; it only moves forward.", "unit"

    # ---- nothing but the name and the width ------------------------------
    return "0", f"{describe_name(name).capitalize()} — {bits}-bit {'unsigned' if ty.startswith('__u') or ty in ('unsigned int','unsigned long') else 'signed'}.", "type"

TYPES_SEEN = set()

# ---- types referenced by keys and values -------------------------------
TYPES = {}
build_constant_tables()

def _member(struct, f):
    ex, dec, basis = example_for(struct, f)
    return {"type": f["type"], "name": f["name"], "bits": f["bits"],
            "note": clean_prose_files(f["note"])[:220],
            "example": ex, "decoded": dec, "basis": basis}

def want_type(t):
    t = (t or "").strip()
    mm = re.match(r"(?:const\s+)?struct\s+([A-Za-z_]\w*)", t)
    if not mm: return
    nm = mm.group(1)
    if nm in TYPES or nm not in STRUCTS: return
    TYPES_SEEN.add(nm)
    st = STRUCTS[nm]
    TYPES[nm] = {"name": "struct " + nm, "file": st["file"], "line": st["line"],
                 "doc": clean_prose_files(st["doc"])[:700],
                 "fields": [_member(nm, f) for f in st["fields"]]}
    for f in st["fields"]:
        want_type(f["type"])

# ---- maps --------------------------------------------------------------
map_out = []
for name, rec in sorted(MAPS.items()):
    fam, blurb = family_of(name, rec["macro"])
    want_type(rec["key"]); want_type(rec["value"])
    prods = sorted(rec["producers"].items(), key=lambda kv: kv[0])
    cons  = sorted(rec["consumers"].items(), key=lambda kv: kv[0])
    map_out.append({
        "name": name, "scope": rec["scope"], "type": rec["type"],
        "family": fam, "blurb": blurb,
        "max_entries": rec["max_entries"], "map_flags": rec["map_flags"],
        "pinned": rec["pinned"],
        "key": rec["key"] or rec["key_size"], "value": rec["value"] or rec["value_size"],
        "file": rec["decl_file"], "line": rec["decl_line"],
        "doc": clean_prose_files(rec["doc"])[:900], "gates": rec["gates"], "macro": rec["macro"],
        "flow": flow_of(rec),
        "owners": sorted(prog_index[o] for o in rec["owners"] if o in prog_index),
        "producers": [{"prog": prog_index[f], "sites": st[:6]} for f, st in prods if f in prog_index],
        "consumers": [{"prog": prog_index[f], "sites": st[:6]} for f, st in cons if f in prog_index],
    })
for i, m in enumerate(map_out):
    for e in m["producers"]: prog_out[e["prog"]]["produces"].append(i)
    for e in m["consumers"]: prog_out[e["prog"]]["consumes"].append(i)

data = {
    "generated": datetime.date.today().isoformat(),
    "source": "crates/bpf",
    "method": ("Parsed from the sources: every `SEC(\".maps\")` declaration, literal or "
               "macro-generated, resolved per program object through its #include graph and "
               "its KESTREL_* feature gates. An edge is an in-kernel map helper call reached "
               "from a SEC() entry, a bpf_timer callback or a bpf_loop callback; a write is "
               "an update/delete/reserve/output/get-with-F_CREATE, or a lookup whose result "
               "the same function writes through or hands back as a writable pointer. "
               "Gates that only a kernel-capability probe sets (KESTREL_NO_*) are taken as "
               "unset, i.e. the capable-kernel build."),
    "counts": {"maps": len(map_out), "programs": len(prog_out),
               "members": sum(len(t["fields"]) for t in TYPES.values()),
               "basis": {k: sum(1 for t in TYPES.values() for f in t["fields"]
                                if f["basis"] == k)
                         for k in ("constants", "source", "unit", "type")},
               "shared": sum(1 for m in map_out if m["scope"] == "shared"),
               "edges": sum(len(m["producers"]) + len(m["consumers"]) for m in map_out)},
    "flow_label": FLOW_LABEL,
    "programs": prog_out, "maps": map_out, "types": TYPES,
}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("const SIGNALS = ")
    json.dump(data, f, separators=(",", ":"), ensure_ascii=False)
    f.write(";\n")
print(f"{OUT}: {data['counts']['maps']} maps, {data['counts']['programs']} programs, "
      f"{data['counts']['edges']} producer/consumer edges, {os.path.getsize(OUT)} bytes")
