#!/usr/bin/env python3
"""Build assets/data/signals.js from the eBPF sources in crates/bpf.

Emits `const SIGNALS = {...};` -- the load-as-a-script convention data.js,
campaigns.js and ebpf.js use, denormalised so the pages render without any
further joining: every map carries its declaration, its key and value shape,
and the programs that write it (producers) or read it (consumers) with the
call site that proves each edge.

WHAT IS PARSED

  * Every `SEC(".maps")` declaration, whether written out in a header or a
    source or generated by a KESTREL_DEFINE_* / TELEMETRY_DEFINE_* macro
    (nested macros are expanded, so KESTREL_DEFINE_PATH_TABLE's side table
    appears under its own name).
  * Each program object's #include graph and its KESTREL_* feature gates,
    evaluated with a small #if/#ifdef evaluator, so a header's map belongs
    only to the objects that actually declare it.
  * Map-helper calls reached from a SEC() entry, a bpf_timer callback or a
    bpf_loop callback. A WRITE is an update / delete / push / ringbuf
    reserve / ringbuf output / storage get with F_CREATE, or a lookup whose
    result the same function writes through or returns as a writable
    pointer. Everything else that touches the map is a READ.

LIMITS, stated so the pages can state them

  * Gates only a kernel-capability probe sets (KESTREL_NO_*) are taken as
    unset: this is the capable-kernel build.
  * Reachability follows calls and macro bodies; a callee hidden behind
    token pasting is reached by name, which over-approximates slightly.
  * Userspace is not analysed. A map with in-kernel readers and no in-kernel
    writer is a control-plane input; one with writers and no readers is
    drained by userspace. Both are reported as such.

    python3 assets/data/source/signals_to_js.py \\
        ../crates/bpf assets/data/signals.js
"""
import datetime, json, os, re, sys

ROOT = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else "../crates/bpf")
OUT  = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else "assets/data/signals.js")
INC  = os.path.join(ROOT, "include")
BPF  = os.path.join(ROOT, "bpf")

rel  = lambda p: os.path.relpath(p, ROOT)
read = lambda p: open(p, encoding="utf-8", errors="replace").read()

# ------------------------------------------------------------------- sources
headers, sources = [], []
for base, dirs, files in os.walk(INC):
    dirs[:] = [d for d in dirs if d != "generated"]
    headers += [os.path.join(base, f) for f in files if f.endswith(".h")]
for base, _d, files in os.walk(BPF):
    sources += [os.path.join(base, f) for f in files if f.endswith(".c")]
headers.sort(); sources.sort()
TEXT = {p: read(p) for p in headers + sources}
BYNAME = {os.path.basename(p): p for p in headers}
BYREL  = {os.path.relpath(p, INC): p for p in headers}

def strip_comments(s):
    """Blank out comments, preserving every offset and newline."""
    out, i, n = list(s), 0, len(s)
    def blank(a, b):
        for k in range(a, b):
            if out[k] != "\n": out[k] = " "
    while i < n:
        if s.startswith("/*", i):
            j = s.find("*/", i + 2); j = n if j < 0 else j + 2
            blank(i, j); i = j
        elif s.startswith("//", i):
            j = s.find("\n", i); j = n if j < 0 else j
            blank(i, j); i = j
        elif s[i] in "\"'":
            q = s[i]; i += 1
            while i < n and s[i] != q:
                if s[i] == "\\": i += 1
                i += 1
            i += 1
        else:
            i += 1
    return "".join(out)

CODE = {p: strip_comments(t) for p, t in TEXT.items()}
lineno = lambda text, pos: text.count("\n", 0, pos) + 1

def clean_prose(body):
    lines = [re.sub(r"^\s*\*\s?", "", ln).strip() for ln in body.split("\n")]
    return re.sub(r"\s+", " ", " ".join(x for x in lines if x)).strip()

def doc_before(text, pos):
    """The comment block above `pos`, looking past #if/#define and blank lines."""
    head = text[:pos]
    skipped = 0
    while True:
        stripped = head.rstrip()
        if stripped.endswith("*/"):
            start = stripped.rfind("/*")
            if start < 0: return ""
            return clean_prose(stripped[start + 2: -2])
        nl = stripped.rfind("\n")
        line = stripped[nl + 1:].strip()
        if skipped >= 3 or (line and not re.match(r"#\s*(if|ifdef|ifndef|else|elif|endif)\b", line)):
            return ""
        skipped += 1
        head = stripped[:nl + 1]

# -------------------------------------------------------------- struct/enums
STRUCTS, ENUMS = {}, {}
FIELD_RE = re.compile(
    r"^(?P<type>(?:const |volatile |unsigned |signed |struct |union |enum )*"
    r"[A-Za-z_][A-Za-z_0-9]*\s*\**)\s*(?P<name>[A-Za-z_][A-Za-z_0-9]*)"
    r"(?P<arr>(?:\s*\[[^\]]*\])*)\s*(?::\s*(?P<bits>\d+))?$")
SKIP_TY = {"return", "if", "else", "static", "_Static_assert", "typedef"}

def comments_in(chunk):
    """[(start, text)] for every comment in `chunk`, in order."""
    out = []
    for m in re.finditer(r"/\*(.*?)\*/|//([^\n]*)", chunk, re.S):
        out.append((m.start(), clean_prose(m.group(1) or m.group(2))))
    return out

def parse_struct_body(body):
    """Members of a struct, each with the comment the source keeps beside it.

    A comment that sits on the same line as the PREVIOUS member's semicolon is
    that member's trailing note, not the next one's opening remark -- without
    that split, `__u64 x; /* about x */` would document the field after x."""
    fields, bare, start = [], strip_comments(body), 0
    for m in re.finditer(r";", bare):
        raw, start = body[start:m.start()], m.end()
        if not raw.strip(): continue
        nl = raw.find("\n")
        notes, trailing = [], []
        for at, txt in comments_in(raw):
            (trailing if (nl >= 0 and at < nl) else notes).append(txt)
        if trailing and fields:
            fields[-1]["note"] = re.sub(r"\s+", " ",
                (fields[-1]["note"] + " " + " ".join(trailing)).strip())
        clean = re.sub(r"\s+", " ", strip_comments(raw)).strip()
        if not clean or "(" in clean: continue
        fm = FIELD_RE.match(clean)
        if not fm: continue
        ty = re.sub(r"\s+", " ", fm.group("type")).strip()
        if ty.split()[0] in SKIP_TY: continue
        fields.append({"type": ty,
                       "name": fm.group("name") + (fm.group("arr") or "").replace(" ", ""),
                       "bits": fm.group("bits"),
                       "note": re.sub(r"\s+", " ", " ".join(notes)).strip()})
    return fields

for p in headers + sources:
    t = TEXT[p]
    for m in re.finditer(r"\bstruct\s+([A-Za-z_][A-Za-z_0-9]*)\s*\{", t):
        name, i, depth = m.group(1), m.end() - 1, 0
        for j in range(i, len(t)):
            if t[j] == "{": depth += 1
            elif t[j] == "}":
                depth -= 1
                if depth == 0: break
        else: continue
        if 'SEC(".maps")' in t[j + 1: j + 40]: continue
        if name in STRUCTS: continue
        STRUCTS[name] = {"file": rel(p), "line": lineno(t, m.start()),
                         "doc": doc_before(t, m.start()),
                         "fields": parse_struct_body(t[i + 1: j])}
    for m in re.finditer(r"\benum\s+([A-Za-z_][A-Za-z_0-9]*)\s*\{([^}]*)\}", t, re.S):
        if m.group(1) in ENUMS: continue
        vals = []
        for item in m.group(2).split(","):
            note = " ".join(x.strip() for pair in
                            re.findall(r"/\*(.*?)\*/|//([^\n]*)", item, re.S)
                            for x in pair if x)
            c = re.sub(r"\s+", " ", strip_comments(item)).strip()
            mm = re.match(r"([A-Za-z_][A-Za-z_0-9]*)\s*(?:=\s*(.+))?$", c)
            if mm: vals.append({"name": mm.group(1), "value": (mm.group(2) or "").strip(),
                                "note": re.sub(r"\s+", " ", note).strip()})
        ENUMS[m.group(1)] = {"file": rel(p), "line": lineno(t, m.start()),
                             "doc": doc_before(t, m.start()), "values": vals}

# ------------------------------------------------------------ #if/#endif map
def directives(text):
    out = []
    for m in re.finditer(r"^[ \t]*#[ \t]*(ifdef|ifndef|if|elif|else|endif|define)\b"
                         r"((?:[^\n\\]|\\\n|\\)*)", text, re.M):
        out.append((m.start(), m.end(), m.group(1),
                    re.sub(r"\s+", " ", m.group(2).replace("\\\n", " ")).strip()))
    return out
DIRS = {p: directives(TEXT[p]) for p in headers + sources}

def guards_at(dd, pos):
    stack = []
    for at, _e, kind, expr in dd:
        if at > pos: break
        if kind == "ifdef":    stack.append(expr.split()[0] if expr else "")
        elif kind == "ifndef": stack.append("!" + (expr.split()[0] if expr else ""))
        elif kind == "if":
            g = re.findall(r"defined\s*\(?\s*([A-Za-z_][A-Za-z_0-9]*)", expr)
            stack.append(g[0] if len(g) == 1 and "!" not in expr else "")
        elif kind in ("elif", "else"):
            if stack: stack[-1] = ""
        elif kind == "endif":
            if stack: stack.pop()
        else:
            continue
    return [g for g in stack if g and g.startswith("KESTREL_")]

# ------------------------------------------------------------ map templates
ATTRS = {"type": r"__uint\(\s*type\s*,\s*([A-Za-z_0-9]+)\s*\)",
         "max_entries": r"__uint\(\s*max_entries\s*,\s*([^)]+)\)",
         "map_flags": r"__uint\(\s*map_flags\s*,\s*([^)]+)\)",
         "pinning": r"__uint\(\s*pinning\s*,\s*([^)]+)\)",
         "key_size": r"__uint\(\s*key_size\s*,\s*([^)]+)\)",
         "value_size": r"__uint\(\s*value_size\s*,\s*([^)]+)\)",
         "key": r"__type\(\s*key\s*,\s*([^)]+)\)",
         "value": r"__type\(\s*value\s*,\s*([^)]+)\)",
         "values": r"__array\(\s*values\s*,\s*([^)]+)\)"}

def parse_attrs(body):
    out = {}
    for k, rx in ATTRS.items():
        m = re.search(rx, body)
        if m: out[k] = re.sub(r"[\s\\]+", " ", m.group(1)).strip()
    return out

MAPDECL = re.compile(
    r"struct\s*\{(?P<body>.*?)\}\s*(?P<name>[A-Za-z_][A-Za-z_0-9#]*)\s*SEC\(\"\.maps\"\)\s*;?",
    re.S)

RAW = []
for p in headers + sources:
    t = TEXT[p]
    for m in MAPDECL.finditer(t):
        RAW.append({"decl": m.group("name"), "file": rel(p), "abs": p,
                    "line": lineno(t, m.start()),
                    "attrs": parse_attrs(strip_comments(m.group("body"))),
                    "doc": doc_before(t, m.start()),
                    "gates": guards_at(DIRS[p], m.start())})

TEMPLATES = {d["decl"]: d for d in RAW if "##" in d["decl"] or d["decl"] == "name"}
LITERALS  = [d for d in RAW if d["decl"] not in TEMPLATES]

# which macro owns which template declaration
MACRO_OF_TEMPLATE = {}
def macro_bodies():
    out = {}
    for p in headers:
        t = TEXT[p]
        for m in re.finditer(r"^#define\s+([A-Z][A-Z_0-9]+)\(([^)]*)\)", t, re.M):
            i = m.end(); body = []
            for ln in t[i:].split("\n"):
                body.append(ln)
                if not ln.rstrip().endswith("\\"): break
            out[m.group(1)] = {"params": [x.strip() for x in m.group(2).split(",")],
                               "body": "\n".join(body), "file": rel(p),
                               "line": lineno(t, m.start())}
    return out
MACROS = macro_bodies()
for mname, mm in MACROS.items():
    for d in MAPDECL.finditer(mm["body"]):
        MACRO_OF_TEMPLATE[d.group("name")] = mname

# ------------------------------------------------------- per-program sources
DOMAIN = {"bpf": "core", "actionable": "actionable", "telemetry": "telemetry"}
INCRE  = re.compile(r'^[ \t]*#[ \t]*include[ \t]*"([^"]+)"', re.M)

def resolve_include(name):
    if name in BYREL: return BYREL[name]
    b = os.path.basename(name)
    return BYNAME.get(b)

PROGS = []
for p in sources:
    t, c = TEXT[p], CODE[p]
    d = os.path.basename(os.path.dirname(p))
    domain = DOMAIN.get(d, "core")
    stem = os.path.basename(p)[:-2]
    # includes, transitively
    seen, queue = set(), [p]
    while queue:
        f = queue.pop()
        for inc in INCRE.findall(TEXT[f]):
            r = resolve_include(inc)
            if r and r not in seen:
                seen.add(r); queue.append(r)
    # gates
    gates = set(re.findall(r"^[ \t]*#[ \t]*define[ \t]+(KESTREL_[A-Z_0-9]+)", t, re.M))
    # macro instantiations
    insts = [(m.group(1), [a.strip() for a in m.group(2).split(",")])
             for m in re.finditer(r"^([A-Z][A-Z_0-9]+)\(([^)]*)\)", t, re.M)
             if m.group(1) not in ("SEC",)]
    base = None
    for mac, args in insts:
        if mac in ("KESTREL_DEFINE_CTL", "KESTREL_DEFINE_DROPS", "KESTREL_DEFINE_LANE_RESERVE"):
            base = args[0]; break
    # SEC() attach points
    secs = []
    for m in re.finditer(r'SEC\("([^"]+)"\)\s*(?:\n|\r\n)?\s*([^\n{;]*)', t):
        s = m.group(1)
        if s in (".maps", "license", "version"): continue
        sig = re.sub(r"\s+", " ", m.group(2)).strip()
        fn = re.search(r"([A-Za-z_][A-Za-z_0-9]*)\s*\(", sig)
        secs.append({"sec": s, "fn": fn.group(1) if fn else ""})
    PROGS.append({"file": rel(p), "abs": p, "domain": domain, "stem": stem,
                  "base": base or stem, "includes": sorted(rel(x) for x in seen),
                  "inc_abs": seen, "gates": sorted(gates), "insts": insts,
                  "secs": secs,
                  "doc": clean_prose(re.sub(r"^//\s?", "",
                        "\n".join(ln[2:].lstrip() if ln.startswith("//") else ""
                                  for ln in t.split("\n")[:14] if ln.startswith("//"))))})

# program display names & rows from the composition table
ROWS = {}
pt = TEXT[os.path.join(INC, "kestrel_programs.h")]
for m in re.finditer(r"#define\s+KESTREL_ROW_([A-Z_0-9]+)\s+([^\n]+)", pt):
    cells = [x.strip() for x in m.group(2).split(",")]
    if len(cells) < 4: continue
    ROWS[cells[0]] = {"program": m.group(1), "class": cells[1],
                      "ctx": cells[2], "lane": cells[3]}

# ------------------------------------------------------- concrete map set
MAPS = {}   # key: (name, owner) -> record

def add_map(name, tmpl, owner, kind, extra=None):
    """owner: None for a shared singleton, else the program file."""
    shared = owner is None
    k = name
    rec = MAPS.get(k)
    if rec is None:
        rec = MAPS[k] = {
            "name": name, "scope": kind,
            "type": (tmpl["attrs"].get("type") or "").replace("BPF_MAP_TYPE_", ""),
            "max_entries": tmpl["attrs"].get("max_entries", ""),
            "map_flags": tmpl["attrs"].get("map_flags", ""),
            "pinned": "pinning" in tmpl["attrs"],
            "key": tmpl["attrs"].get("key", ""),
            "value": tmpl["attrs"].get("value") or tmpl["attrs"].get("values", ""),
            "key_size": tmpl["attrs"].get("key_size", ""),
            "value_size": tmpl["attrs"].get("value_size", ""),
            "decl_file": tmpl["file"], "decl_line": tmpl["line"],
            "doc": tmpl["doc"], "gates": tmpl["gates"],
            "macro": MACRO_OF_TEMPLATE.get(tmpl["decl"], ""),
            "owners": [], "producers": {}, "consumers": {}, "sites": [],
        }
        if extra: rec.update(extra)
    if owner and owner not in rec["owners"]:
        rec["owners"].append(owner)
    return rec

def subst(s, params, args):
    for p_, a in zip(params, args):
        s = re.sub(r"\b%s\b" % re.escape(p_), a, s)
    return s

# 1. maps declared literally in a program source
for pr in PROGS:
    for d in LITERALS:
        if d["abs"] == pr["abs"]:
            add_map(d["decl"], d, pr["file"], "program")

# 2. maps declared literally in a header, instantiated per including program
for d in LITERALS:
    if not d["abs"].startswith(INC): continue
    owners = [pr for pr in PROGS
              if d["abs"] in pr["inc_abs"] and all(g in pr["gates"] for g in d["gates"])]
    if not owners: continue
    if "pinning" in d["attrs"] or d["decl"] == "sockmap":
        rec = add_map(d["decl"], d, None, "shared")
        rec["owners"] = [o["file"] for o in owners]
        rec["declared_by"] = [o["file"] for o in owners]
    else:
        for o in owners:
            add_map(d["decl"], d, o["file"], "per-object")

# 3. macro-instantiated maps
def expand_macro(mac, args, depth=0):
    """Yield (macro_name, body_text_with_args_substituted) one nesting deep."""
    mm = MACROS.get(mac)
    if not mm or depth > 2: return
    body = subst(mm["body"], mm["params"], args)
    yield mac, mm, body
    for nested in re.finditer(r"^\s*(KESTREL_[A-Z_0-9]+)\(([^)]*)\)", body, re.M):
        nm = nested.group(1)
        if nm == mac or nm not in MACROS: continue
        yield from expand_macro(nm, [a.strip() for a in nested.group(2).split(",")], depth + 1)

for pr in PROGS:
    seen_inst = set()
    for mac0, args0 in pr["insts"]:
      for mac, mm, mbody in expand_macro(mac0, args0):
        if (mac, tuple(mm["params"])) in seen_inst and False: continue
        for d in MAPDECL.finditer(mbody):
            nm = d.group("name").replace("##", "")
            tmpl = {"decl": d.group("name"), "file": mm["file"], "line": mm["line"],
                    "attrs": parse_attrs(strip_comments(d.group("body"))), "gates": [],
                    "doc": doc_before(TEXT[os.path.join(ROOT, mm["file"])],
                                      TEXT[os.path.join(ROOT, mm["file"])].find("#define " + mac))}
            add_map(nm, tmpl, pr["file"], "program")
    # the four shared lane rings, from KESTREL_DEFINE_LANE in kestrel_shared_maps.h
# 4. the lane rings (macro invoked in a header, not a source)
sm = os.path.join(INC, "kestrel_shared_maps.h")
lane_mm = MACROS.get("KESTREL_DEFINE_LANE")
lane_users = [pr["file"] for pr in PROGS
              if sm in pr["inc_abs"] and "KESTREL_USE_DATA_PLANE_MAPS" in pr["gates"]]
if lane_mm:
    for m in re.finditer(r"^KESTREL_DEFINE_LANE\(([A-Za-z_0-9]+)\);", TEXT[sm], re.M):
        nm = m.group(1)
        d = list(MAPDECL.finditer(lane_mm["body"]))[-1]
        tmpl = {"decl": nm, "file": rel(sm), "line": lineno(TEXT[sm], m.start()),
                "attrs": parse_attrs(subst(strip_comments(d.group("body")),
                                           lane_mm["params"], [nm])),
                "gates": ["KESTREL_USE_DATA_PLANE_MAPS"],
                "doc": doc_before(TEXT[sm], TEXT[sm].find("#define KESTREL_DEFINE_LANE"))}
        rec = add_map(nm, tmpl, None, "shared")
        rec["owners"] = list(lane_users)
        rec["value"] = "struct %s_ring (RINGBUF)" % nm
        rec["macro"] = "KESTREL_DEFINE_LANE"

# ======================================================================
#  ACCESS ANALYSIS
# ======================================================================
# ---- map-helper vocabulary and the write-through heuristic ----------

# helper -> (role, arg index of the map)
READ  = "consume"
WRITE = "produce"
HELPERS = {
    "bpf_map_lookup_elem":        (READ,  0),
    "bpf_map_lookup_percpu_elem": (READ,  0),
    "bpf_get_local_storage":      (READ,  0),
    "bpf_for_each_map_elem":      (READ,  0),
    "bpf_ringbuf_query":          (READ,  0),
    "bpf_tail_call":              (READ,  1),
    "bpf_redirect_map":           (READ,  0),
    "bpf_sk_redirect_map":        (READ,  1),
    "bpf_msg_redirect_map":       (READ,  1),
    "bpf_sk_select_reuseport":    (READ,  1),
    "bpf_map_update_elem":        (WRITE, 0),
    "bpf_map_delete_elem":        (WRITE, 0),
    "bpf_map_push_elem":          (WRITE, 0),
    "bpf_map_pop_elem":           (WRITE, 0),
    "bpf_ringbuf_reserve":        (WRITE, 0),
    "bpf_ringbuf_output":         (WRITE, 0),
    "bpf_perf_event_output":      (WRITE, 1),
    "bpf_get_stackid":            (WRITE, 1),
    "bpf_task_storage_delete":    (WRITE, 0),
    "bpf_sk_storage_delete":      (WRITE, 0),
    "bpf_sock_map_update":        (WRITE, 1),
    "bpf_sock_hash_update":       (WRITE, 1),
    "bpf_timer_init":             (WRITE, 1),
    # get-or-create: role decided from the flags argument
    "bpf_task_storage_get":       ("storage", 0),
    "bpf_sk_storage_get":         ("storage", 0),
    "bpf_cgrp_storage_get":       ("storage", 0),
    "bpf_inode_storage_get":      ("storage", 0),
}
CALL = re.compile(r"\b(bpf_[a-z_0-9]+|kestrel_help_[a-z_0-9]+)\s*\(")

def split_args(s, start):
    """args of a call whose '(' is at start-1; returns (list, end)."""
    depth, i, cur, out = 1, start, [], []
    while i < len(s) and depth:
        ch = s[i]
        if ch in "([": depth += 1
        elif ch in ")]":
            depth -= 1
            if depth == 0: break
        if depth == 1 and ch == ",":
            out.append("".join(cur).strip()); cur = []
        else:
            cur.append(ch)
        i += 1
    out.append("".join(cur).strip())
    return out, i

# callees whose first argument is an OUT parameter: passing the looked-up
# pointer (or a member of it) to one of these is a write through the map.
OUT_PARAM = (r"(?:__builtin_mem(?:set|cpy|move)|bpf_probe_read\w*|bpf_core_read\w*|"
             r"bpf_skb_load_bytes\w*|bpf_get_current_comm|bpf_d_path|bpf_get_func_arg\w*|"
             r"bpf_sysctl_get_\w+|bpf_snprintf\w*|bpf_ringbuf_(?:reserve|output|submit|discard)|"
             r"bpf_map_(?:update|delete)_elem|bpf_perf_event_read_value|bpf_get_stack\w*|"
             r"kestrel_help_(?:probe_read\w*|skb_load_bytes|get_current_comm|sysctl_get_\w+))")

def mutates(body, var):
    """Does the body write through `var`, the pointer a lookup returned?"""
    v = re.escape(var)
    member = rf"{v}\s*(?:->|\.)\s*\w+(?:\s*\[[^\]]*\])?(?:\s*(?:->|\.)\s*\w+(?:\s*\[[^\]]*\])?)*"
    pats = [
        rf"\*\s*{v}\s*(?:\+\+|--|[-+*/|&^%]?=(?!=))",
        rf"(?<![\w.>]){member}\s*(?:\+\+|--|[-+*/|&^%]?=(?!=))",
        rf"(?:\+\+|--)\s*\*?\s*(?:{member}|{v})\b",
        rf"__sync_fetch_and_\w+\s*\(\s*&\s*(?:{member}|{v})\s*[,)]",
        rf"{OUT_PARAM}\s*\(\s*&?\s*(?:{member}|{v})\s*[,)\[]",
    ]
    return any(re.search(p, body) for p in pats)

def scan_calls(body):
    """Yield (helper, args, pos) for every map helper call in `body`."""
    for m in CALL.finditer(body):
        name = m.group(1)
        args, end = split_args(body, m.end())
        yield name, args, m.start()

ALLGATES = set()
for pr in PROGS: ALLGATES |= set(pr["gates"])

# every function-like macro, as a pseudo-function: a call written inside a
# macro body (KESTREL_DP_PROLOGUE_FOLD -> dp_ctl, dp_reserve) still reaches.
MACRO_FUNCS = {}
for p in headers + sources:
    t = TEXT[p]
    for m in re.finditer(r"^#define\s+([A-Za-z_]\w*)\(([^)]*)\)", t, re.M):
        i = m.end(); body = []
        for ln in t[i:].split("\n"):
            body.append(ln)
            if not ln.rstrip().endswith("\\"): break
        MACRO_FUNCS.setdefault(m.group(1), []).append(
            (rel(p), strip_comments("\n".join(body).replace("\\\n", "\n"))))

SAFE = re.compile(r"^[0-9()!&|<>=+\-*/% ]*$")

def _eval(expr, defs, known):
    """Evaluate a #if expression. Returns True / False / None (undecidable)."""
    e = expr
    e = re.sub(r"defined\s*\(\s*([A-Za-z_]\w*)\s*\)", lambda m: _d(m.group(1), defs, known), e)
    e = re.sub(r"defined\s+([A-Za-z_]\w*)", lambda m: _d(m.group(1), defs, known), e)
    for _ in range(4):
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b",
                    lambda m: defs.get(m.group(1), m.group(1)), e)
        if e2 == e: break
        e = e2
    e = e.replace("&&", " and ").replace("||", " or ").replace("!=", " __NE__ ")
    e = re.sub(r"!", " not ", e).replace("__NE__", "!=")
    if re.search(r"[A-Za-z_]", e.replace(" and ", " ").replace(" or ", " ").replace(" not ", " ")):
        return None
    try:
        return bool(eval(e, {"__builtins__": {}}, {}))
    except Exception:
        return None

def _d(sym, defs, known):
    if sym in defs: return "1"
    if sym in known: return "0"
    if sym.startswith(("KESTREL_", "TELEMETRY_")): return "0"
    return sym            # undecidable -> leaves an identifier behind

def filter_by_gates(text, dd, gates, defs=None):
    """Blank the regions of `text` this program's defines exclude."""
    out = list(text)
    if defs is None: defs = {g: "1" for g in gates}
    known = set(ALLGATES)
    stack = []            # {state: True/False/None, done: bool, start: int}
    def blank(a, b):
        for i in range(a, min(b, len(out))):
            if out[i] != "\n": out[i] = " "
    for at, end, kind, expr in dd:
        if kind == "define":
            if stack and any(f["state"] is False for f in stack): continue
            m = re.match(r"([A-Za-z_]\w*)\s*(?:\(|$|\s)(.*)", expr)
            if m and "(" not in expr[:len(m.group(1)) + 1] and not m.group(1).endswith("_H"):
                val = m.group(2).strip()
                if val == "": defs[m.group(1)] = "1"
                elif SAFE.match(val): defs[m.group(1)] = "(" + val + ")"
                known.add(m.group(1))
            continue
        if kind in ("ifdef", "ifndef", "if"):
            if kind == "ifdef":   v = _eval("defined(%s)" % (expr.split() or [""])[0], defs, known)
            elif kind == "ifndef": v = _eval("!defined(%s)" % (expr.split() or [""])[0], defs, known)
            else:                  v = _eval(expr, defs, known)
            stack.append({"state": v, "done": v is True, "start": end})
            continue
        if not stack: continue
        fr = stack[-1]
        if fr["state"] is False:
            blank(fr["start"], at)
        if kind == "elif":
            v = None if fr["done"] else _eval(expr, defs, known)
            if fr["done"]: v = False
            fr["state"] = v
            fr["done"] = fr["done"] or (v is True)
            fr["start"] = end
        elif kind == "else":
            fr["state"] = False if fr["done"] else (None if fr["state"] is None else True)
            fr["start"] = end
        elif kind == "endif":
            stack.pop()
    return "".join(out)

KW_NOT_FN = {"if","for","while","switch","return","sizeof","do","else","case",
             "defined","__builtin_expect","typeof","_Static_assert"}

def functions_in(text):
    """name -> [body], for every function definition in `text`."""
    out = {}
    for m in re.finditer(r"\)\s*\{", text):
        # walk back to the matching '('
        j = m.start(); depth = 0; i = j
        while i >= 0:
            if text[i] == ")": depth += 1
            elif text[i] == "(":
                depth -= 1
                if depth == 0: break
            i -= 1
        if i < 0: continue
        k = i - 1
        while k >= 0 and text[k] in " \t\n\\": k -= 1
        e = k + 1
        while k >= 0 and (text[k].isalnum() or text[k] == "_"): k -= 1
        name = text[k + 1:e]
        if not name or name in KW_NOT_FN or name[0].isdigit(): continue
        # something must precede the name on the declaration (a return type)
        q = k
        while q >= 0 and text[q] in " \t\n\\*": q -= 1
        if q < 0 or not (text[q].isalnum() or text[q] in "_>"): continue
        if text[q] == ">" or (q > 0 and text[q - 1] == "."): continue
        o = m.end() - 1; depth = 0; jj = -1
        for t_ in range(o, len(text)):
            if text[t_] == "{": depth += 1
            elif text[t_] == "}":
                depth -= 1
                if depth == 0: jj = t_; break
        flat = text.find("\n}", o)
        if jj < 0 or (flat >= 0 and jj > flat + 1): jj = flat + 1
        if jj <= o: continue
        out.setdefault(name, []).append((text[o + 1: jj], k + 1))
    return out

IDENT = re.compile(r"\b([A-Za-z_]\w*)\s*\(")

def analyse(pr):
    """Returns {map_name: {'roles': set, 'sites': [...]}} for one program."""
    gates = set(pr["gates"])
    files = [pr["abs"]] + sorted(pr["inc_abs"])
    defs = {g: "1" for g in gates}
    for _pass in (0, 1):
        units = []
        for f in files:
            units.append((rel(f), filter_by_gates(CODE[f], DIRS[f], gates, defs)))
    own = units[0][1]
    # macro instantiations, substituted
    for mac, args in pr["insts"]:
        mm = MACROS.get(mac)
        if not mm: continue
        body = mm["body"].replace("\\\n", "\n")
        body = subst(strip_comments(body), mm["params"], args).replace("##", "")
        units.append((mm["file"] + " :: " + mac + "(" + args[0] + ")", body))

    funcs, roots = {}, set()
    for label, txt in units:
        for nm, bodies in functions_in(txt).items():
            for b, at in bodies:
                funcs.setdefault(nm, []).append((label, b))
                head = txt[max(0, at - 400):at]
                k = head.rfind("SEC(")
                if k >= 0:
                    tail = head[k:]
                    if ('SEC(".maps")' not in tail and 'SEC("license")' not in tail
                            and tail.count("{") == 0 and tail.count(";") == 0):
                        roots.add(nm)

    for sd in pr["secs"]:
        if sd["fn"]: roots.add(sd["fn"])
    # BPF_PROG()/BPF_KPROBE() wrappers name the function in the macro args
    for m in re.finditer(r"BPF_(?:PROG|KPROBE|KRETPROBE|KSYSCALL)\s*\(\s*([A-Za-z_]\w*)", own):
        roots.add(m.group(1))
    # timer callbacks are reached from bpf_timer_set_callback()
    for _l, txt in units:
        for m in re.finditer(r"bpf_timer_set_callback\s*\([^,]+,\s*([A-Za-z_]\w*)", txt):
            roots.add(m.group(1))
    for mac, args in pr["insts"]:
        for a in args:
            if re.fullmatch(r"[a-z_]\w*", a): roots.add(a)
    for nm, defs_ in MACRO_FUNCS.items():
        for label, body in defs_:
            funcs.setdefault(nm, []).append((label + " (macro)", body))
    roots &= set(funcs)
    reach, queue = set(roots), list(roots)
    while queue:
        fn = queue.pop()
        for label, body in funcs.get(fn, []):
            for m in IDENT.finditer(body):
                nm = m.group(1)
                if nm in funcs and nm not in reach:
                    reach.add(nm); queue.append(nm)
            # token-pasted macro calls (KESTREL_FV_CAST_##cast(...)) hide the
            # callee behind ##, so any known UPPERCASE macro named in the body
            # counts as reached.
            for m in re.finditer(r"\b(\w{3,})\b", body):
                nm = m.group(1)
                if nm in funcs and nm not in reach:
                    reach.add(nm); queue.append(nm)

    hits = {}
    def note(mapname, role, site):
        e = hits.setdefault(mapname, {"roles": set(), "sites": []})
        e["roles"].add(role)
        if site not in e["sites"]: e["sites"].append(site)

    for fn in sorted(reach):
        for label, body in funcs.get(fn, []):
            for helper, args, pos in scan_calls(body):
                spec = HELPERS.get(helper)
                if not spec:
                    spec = HELPERS.get(helper.replace("kestrel_help_", "bpf_"))
                if not spec: continue
                role, idx = spec
                if idx >= len(args): continue
                a = args[idx].strip()
                m = re.match(r"&\s*([A-Za-z_]\w*)$", a)
                if not m: continue
                mapname = m.group(1)
                if role == "storage":
                    flags = args[3] if len(args) > 3 else ""
                    r = WRITE if "F_CREATE" in flags else READ
                    note(mapname, r, {"fn": fn, "file": label, "helper": helper})
                    if r == WRITE:
                        note(mapname, READ, {"fn": fn, "file": label, "helper": helper})
                    continue
                note(mapname, role, {"fn": fn, "file": label, "helper": helper})
                if helper.endswith("lookup_elem") or helper.endswith("lookup_percpu_elem"):
                    before = body[:pos].replace("\n", " ")
                    mm = re.search(r"(?:^|[;{}()=])\s*([A-Za-z_][\w \t*]*?\b)?(\w+)\s*=\s*$", before)
                    if not mm: continue
                    decl, var = (mm.group(1) or ""), mm.group(2)
                    if not decl:   # assigned to a variable declared earlier
                        dm = re.search(r"\b((?:const\s+)?[\w]+(?:\s+\w+)*\s*\**)\s*%s\s*[;,=]"
                                       % re.escape(var), body)
                        decl = dm.group(1) if dm else ""
                    if "const" in decl: continue
                    tail = body[pos:]
                    if mutates(tail, var):
                        note(mapname, WRITE,
                             {"fn": fn, "file": label, "helper": "lookup + write-through"})
                    elif re.search(r"return\s*(?:\([^)]*\)\s*)?%s\s*;" % re.escape(var), tail):
                        note(mapname, WRITE,
                             {"fn": fn, "file": label,
                              "helper": "lookup returned as a writable pointer"})
    writes_ring = any("bpf_ringbuf_reserve(" in b or "bpf_ringbuf_output(" in b
                      for fn in reach for _l, b in funcs.get(fn, []))
    if writes_ring:
        for mapname, e in hits.items():
            rec = MAPS.get(mapname)
            if rec and rec["type"] == "ARRAY_OF_MAPS":
                e["roles"].add(WRITE)
                e["sites"].append({"fn": "dp_reserve", "file": "include/kestrel_data_plane.h",
                                   "helper": "bpf_ringbuf_reserve on the looked-up ring"})
    return hits, reach, funcs

PROG_MAPS = {}
for pr in PROGS:
    hits, reach, funcs = analyse(pr)
    pr["reach"] = sorted(reach)
    PROG_MAPS[pr["file"]] = hits

# attach edges to the map records
for pr in PROGS:
    for mapname, e in PROG_MAPS[pr["file"]].items():
        rec = MAPS.get(mapname)
        if rec is None: continue
        if rec["scope"] != "shared" and pr["file"] not in rec["owners"]:
            continue
        for role in e["roles"]:
            bucket = "producers" if role == WRITE else "consumers"
            rec[bucket].setdefault(pr["file"], [])
            for s in e["sites"]:
                if s not in rec[bucket][pr["file"]]:
                    rec[bucket][pr["file"]].append(s)

# ======================================================================
#  EMIT
# ======================================================================
PROG_TYPE_RE = re.compile(r"^BPF_PROG_TYPE_([A-Z_0-9]+)$")

FAMILY = [
    (r"_dr$",       "Drop counters",     "Per-cause drop tally; the program's own honesty ledger."),
    (r"_ct$",       "Control block",     "One slot the userspace controller writes and the program reads once per event."),
    (r"_fl$",       "Filter predicates", "The compiled predicate block the in-kernel filter evaluates."),
    (r"_tb$",       "Sample bucket",     "Per-CPU token bucket for the sampling gate."),
    (r"_ag$",       "Aggregate",         "Per-key fold under AGGREGATE mode, drained by userspace."),
    (r"_s\d$",      "Side table",        "Per-file data written once per LRU residency and joined at export."),
    (r"_pp$",       "Policy path ids",   "The AUTHORED prefix id for a file, cached per (dev, ino, tag)."),
    (r"_ps$",       "Probe scratch",     "Per-CPU scratch the policy probe claims for one event."),
    (r"_cfg$",      "Program config",    "The rule set this actionable program enforces."),
    (r"^kestrel_lane_", "Event lane",    "One ARRAY_OF_MAPS per lane; each slot is a per-CPU ring the records go out on."),
    (r"_ev$",       "Record ring",       "The telemetry record stream for this metric."),
    (r"_stats$",    "Live counters",     "The metric's running counters."),
    (r"_shadow$|_shad$", "Shadow counters", "Each counter at the last emit, so a delta is a subtraction."),
    (r"_meta$",     "Stream metadata",   "Schema and interval metadata for the record stream."),
    (r"_timers$",   "Flush timers",      "One bpf_timer per CPU driving the periodic flush."),
    (r"_emit$",     "Emit state",        "Sequence and drop state for the record stream."),
    (r"_hist|hist$", "Histogram",        "Latency or errno histogram buckets."),
    (r"scrat|scratch$", "Scratch",       "Per-CPU scratch buffer; holds nothing between events."),
]
NAMED = {
  "kestrel_task":       ("Task slot",        "The per-task correlation, identity and chain state every task-context program shares."),
  "kestrel_sock":       ("Socket slot",      "Per-socket owner, counters and class, hung off the socket and freed with it."),
  "kestrel_lineage":    ("Lineage seed",     "What a fork hook leaves for the child, taken and deleted by the child's first event."),
  "kestrel_vocab":      ("Vocabulary",       "Interned program and comm strings, keyed by hash; 0 means not in the vocabulary."),
  "kestrel_verdicts":   ("Verdict cache",    "The classifier's published verdicts, keyed by the record signature."),
  "kestrel_ports":      ("Port gate",        "The ports the verdict cache is allowed to answer for."),
  "kestrel_path_class": ("Path classes",     "Longest-prefix classification of a path."),
  "kestrel_policy_path":("Policy prefixes",  "The AUTHORED prefix trie the policy path id comes from."),
  "kestrel_addr_class": ("Address classes",  "Longest-prefix classification of a peer address."),
  "kestrel_block":      ("Block list",       "Entries the response path writes and the enforcers read."),
  "kestrel_templates":  ("Chain templates",  "The compiled corpus chains the template matcher walks."),
  "kestrel_template_index": ("Template index", "Which template nodes an emitter can start."),
  "kestrel_tree":       ("Fitted tree",      "The decision tree the verdict backend evaluates."),
  "kestrel_fv_spec":    ("Feature spec",     "The feature-vector layout, published for userspace."),
  "kestrel_fvsc":       ("Feature scratch",  "Per-CPU feature vector, built per event."),
  "kestrel_baseline":   ("Baseline",         "The per-syscall thresholds the accumulator compares against."),
  "kestrel_host":       ("Host state",       "This host's drift word, written by userspace."),
  "kestrel_attach":     ("Attach ordinal",   "Per-cgroup attach ordinal, so one program can tell its attach points apart."),
  "kestrel_policy_meta":("Policy metadata",  "Generation and layout of the policy the program reads."),
  "kestrel_policy_args":("Argument needles", "Hashed AUTHORED argument needles."),
  "kestrel_argw":       ("Argument walk",    "Per-CPU scratch for the argument walk."),
  "kestrel_policy_witness": ("Policy witness", "Per-CPU witness counters for the policy probe."),
  "kestrel_l7sc":       ("L7 scratch",       "Per-CPU scratch for the L7 classifier."),
  "kestrel_pathc":      ("Path walk buffer", "Per-CPU dentry-walk chain and path buffer."),
  "sockmap":            ("Sockmap",          "The grandfathered socket map; not pinned by name."),
}
def family_of(name, macro):
    if name in NAMED: return NAMED[name]
    for rx, label, blurb in FAMILY:
        if re.search(rx, name): return label, blurb
    return "State", ""

def flow_of(rec):
    p, c = bool(rec["producers"]), bool(rec["consumers"])
    if p and c:  return "kernel-state"
    if p:        return "kernel-output"
    if c:        return "control-input"
    return "declared-only"

FLOW_LABEL = {
    "kernel-state":  "Written and read in kernel",
    "kernel-output": "Written in kernel, drained by userspace",
    "control-input": "Written by userspace, read in kernel",
    "declared-only": "Declared, no reachable in-kernel access",
}

# ---- programs ----------------------------------------------------------
prog_out, prog_index = [], {}
for pr in PROGS:
    stem = pr["stem"]
    m = PROG_TYPE_RE.match(stem)
    if m:
        ptype = "BPF_PROG_TYPE_" + m.group(1)
        title = m.group(1)
    else:
        ptype = ""
        title = stem.upper()
    row = ROWS.get(pr["base"], {})
    secs = sorted({s["sec"] for s in pr["secs"] if s["sec"]})
    prog_index[pr["file"]] = len(prog_out)
    prog_out.append({
        "id": len(prog_out), "file": pr["file"], "base": pr["base"],
        "name": title, "prog_type": ptype, "domain": pr["domain"],
        "class": row.get("class", ""), "ctx": row.get("ctx", ""),
        "lane": row.get("lane", ""),
        "attach": secs, "attach_count": len(pr["secs"]),
        "gates": [g for g in pr["gates"] if g.startswith(("KESTREL_USE_", "KESTREL_HELPER_",
                                                          "KESTREL_PATH", "KESTREL_REACT",
                                                          "KESTREL_POLICY", "KESTREL_TREE"))],
        "doc": pr["doc"][:600],
        "produces": [], "consumes": [],
    })

# ---- types referenced by keys and values -------------------------------
TYPES = {}
def want_type(t):
    t = (t or "").strip()
    mm = re.match(r"(?:const\s+)?struct\s+([A-Za-z_]\w*)", t)
    if not mm: return
    nm = mm.group(1)
    if nm in TYPES or nm not in STRUCTS: return
    st = STRUCTS[nm]
    TYPES[nm] = {"name": "struct " + nm, "file": st["file"], "line": st["line"],
                 "doc": st["doc"][:700],
                 "fields": [{"type": f["type"], "name": f["name"], "bits": f["bits"],
                             "note": f["note"][:220]} for f in st["fields"]]}
    for f in st["fields"]:
        want_type(f["type"])

# ---- maps --------------------------------------------------------------
map_out = []
for name, rec in sorted(MAPS.items()):
    fam, blurb = family_of(name, rec["macro"])
    want_type(rec["key"]); want_type(rec["value"])
    prods = sorted(rec["producers"].items(), key=lambda kv: kv[0])
    cons  = sorted(rec["consumers"].items(), key=lambda kv: kv[0])
    map_out.append({
        "name": name, "scope": rec["scope"], "type": rec["type"],
        "family": fam, "blurb": blurb,
        "max_entries": rec["max_entries"], "map_flags": rec["map_flags"],
        "pinned": rec["pinned"],
        "key": rec["key"] or rec["key_size"], "value": rec["value"] or rec["value_size"],
        "file": rec["decl_file"], "line": rec["decl_line"],
        "doc": rec["doc"][:900], "gates": rec["gates"], "macro": rec["macro"],
        "flow": flow_of(rec),
        "owners": sorted(prog_index[o] for o in rec["owners"] if o in prog_index),
        "producers": [{"prog": prog_index[f], "sites": st[:6]} for f, st in prods if f in prog_index],
        "consumers": [{"prog": prog_index[f], "sites": st[:6]} for f, st in cons if f in prog_index],
    })
for i, m in enumerate(map_out):
    for e in m["producers"]: prog_out[e["prog"]]["produces"].append(i)
    for e in m["consumers"]: prog_out[e["prog"]]["consumes"].append(i)

data = {
    "generated": datetime.date.today().isoformat(),
    "source": "crates/bpf",
    "method": ("Parsed from the sources: every `SEC(\".maps\")` declaration, literal or "
               "macro-generated, resolved per program object through its #include graph and "
               "its KESTREL_* feature gates. An edge is an in-kernel map helper call reached "
               "from a SEC() entry, a bpf_timer callback or a bpf_loop callback; a write is "
               "an update/delete/reserve/output/get-with-F_CREATE, or a lookup whose result "
               "the same function writes through or hands back as a writable pointer. "
               "Gates that only a kernel-capability probe sets (KESTREL_NO_*) are taken as "
               "unset, i.e. the capable-kernel build."),
    "counts": {"maps": len(map_out), "programs": len(prog_out),
               "shared": sum(1 for m in map_out if m["scope"] == "shared"),
               "edges": sum(len(m["producers"]) + len(m["consumers"]) for m in map_out)},
    "flow_label": FLOW_LABEL,
    "programs": prog_out, "maps": map_out, "types": TYPES,
}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("const SIGNALS = ")
    json.dump(data, f, separators=(",", ":"), ensure_ascii=False)
    f.write(";\n")
print(f"{OUT}: {data['counts']['maps']} maps, {data['counts']['programs']} programs, "
      f"{data['counts']['edges']} producer/consumer edges, {os.path.getsize(OUT)} bytes")
