#!/usr/bin/env python3
"""seo.py — keep the pages' search/social metadata, robots.txt and sitemap.xml
in sync with the page table below.

    tools/seo.py            rewrite the head block on every page, robots.txt, sitemap.xml
    tools/seo.py --check    verify only; exit 1 if anything is stale or missing

Everything between the SEO_START/SEO_END markers in a page's <head> is
generated, so editing the table here and re-running is the way to change a
title, a description or a piece of structured data. Nothing outside the
markers is touched.

tools/build-assets.sh --seo runs this; the pre-commit hook runs it whenever a
page or this file is staged.
"""

import glob
import html
import json
import os
import re
import subprocess
import sys

SITE = "https://kestrel-signals.io"
NAME = "Kestrel"
TAGLINE = "Signal focus, precision response"
OG_IMAGE = f"{SITE}/assets/img/og-card.png"
OG_ALT = "Kestrel — signal focus, precision response"
THEME = "#1c1c16"

SEO_START = "<!-- seo:start — generated by tools/seo.py; edit the table there -->"
SEO_END = "<!-- seo:end -->"

# Sections used for the breadcrumb trail; they mirror the site's nav rows.
REFERENCES = ("References", None)
DATASETS = ("Datasets", "dataset.html")

# file -> page record.
#   title     <title> and og:title. Descriptive first, brand last.
#   desc      meta description / og:description. Aim for 120-158 characters.
#   crumb     label in the breadcrumb trail, or None for the home page.
#   section   parent section for the breadcrumb, or None for a top-level page.
#   ld        extra JSON-LD node for the page, or None.
#   priority  sitemap priority.
#   freq      sitemap changefreq.
PAGES = {
    "index.html": dict(
        title="Kestrel // Linux Detection Engineering and Signal Analysis",
        desc="Kestrel joins MITRE ATT&CK to what a Linux host can actually "
             "produce: technique-to-analytic coverage, eBPF attach points and "
             "real-time signal classification.",
        crumb=None, section=None, priority="1.0", freq="weekly",
        ld=None,
    ),
    "journey.html": dict(
        title="Journey — Development Journal // Kestrel",
        desc="Kestrel's development journal: design decisions, research notes "
             "and progress on Linux detection engineering, searchable by date "
             "or entry.",
        crumb="Journey", section=None, priority="0.8", freq="weekly",
        ld=lambda url: {
            "@type": "Blog",
            "@id": url + "#blog",
            "name": "Kestrel Journey",
            "description": "Development journal — design decisions, research "
                           "notes and progress.",
            "url": url,
            "inLanguage": "en",
        },
    ),

    # ---- References ----------------------------------------------------
    "visualized.html": dict(
        title="ATT&CK® Coverage Visualized — Linux Techniques // Kestrel",
        desc="Interactive graph of MITRE ATT&CK v19 reduced to its Linux "
             "surface and resolved down to detection strategies, analytics and "
             "data components.",
        crumb="ATT&CK® Visualized", section=REFERENCES,
        priority="0.9", freq="monthly", ld=None,
    ),
    "matrix.html": dict(
        title="ATT&CK® Matrix for Linux Telemetry // Kestrel",
        desc="Filterable MITRE ATT&CK matrix joining Linux tactics, techniques "
             "and analytics to the data components and event keys a sensor can "
             "actually produce.",
        crumb="ATT&CK® Matrix", section=REFERENCES,
        priority="0.9", freq="monthly", ld=None,
    ),
    "campaigns-visualized.html": dict(
        title="ATT&CK® Campaigns Visualized — Linux Threats // Kestrel",
        desc="Linux-targeting ATT&CK campaigns plotted against telemetry "
             "coverage: which documented techniques have actually been used, "
             "and what can observe them.",
        crumb="ATT&CK® Campaigns Visualized", section=REFERENCES,
        priority="0.8", freq="monthly", ld=None,
    ),
    "campaigns.html": dict(
        title="Linux-Targeting ATT&CK® Campaigns // Kestrel",
        desc="MITRE ATT&CK v19 campaigns crossed with Linux telemetry "
             "coverage. Expand a technique for its analytic, data component, "
             "event key and eBPF detail.",
        crumb="ATT&CK® Campaigns", section=REFERENCES,
        priority="0.8", freq="monthly", ld=None,
    ),
    "ebpf.html": dict(
        title="eBPF Program Types Visualized — Attach Points // Kestrel",
        desc="Interactive graph of eBPF program types, helpers, map types and "
             "kfuncs — what the Linux kernel will actually let a detection "
             "observe, and from where.",
        crumb="eBPF Visualized", section=REFERENCES,
        priority="0.8", freq="monthly", ld=None,
    ),
    "ebpf-matrix.html": dict(
        title="eBPF Capability Matrix — Helpers, Maps, Kfuncs // Kestrel",
        desc="Filterable matrix of eBPF program types against the helpers, "
             "maps, kfuncs and syscall commands each may call, with kernel "
             "version floors and verifier scope.",
        crumb="eBPF Matrix", section=REFERENCES,
        priority="0.8", freq="monthly", ld=None,
    ),
    "signals-visualized.html": dict(
        title="eBPF Signal Map Graph — Producers and Consumers // Kestrel",
        desc="Interactive graph of Kestrel's eBPF map inventory: every "
             "SEC(\".maps\") declaration with the programs that write to it and "
             "the ones that read it.",
        crumb="Signals Visualized", section=REFERENCES,
        priority="0.7", freq="monthly", ld=None,
    ),
    "signals-matrix.html": dict(
        title="eBPF Signal Map Matrix — Scope, Keys, Flows // Kestrel",
        desc="Filterable inventory of Kestrel's eBPF maps by family, type and "
             "scope, with key/value pairs, producers, consumers and the "
             "direction data flows.",
        crumb="Signals Matrix", section=REFERENCES,
        priority="0.7", freq="monthly", ld=None,
    ),

    # ---- Datasets ------------------------------------------------------
    "dataset.html": dict(
        title="Datasets — Four Corpora, One Provenance Chain // Kestrel",
        desc="The four bodies of data behind every claim on this site: the "
             "ATT&CK framework, a Linux reference map, living-off-the-land "
             "binaries and eBPF capability.",
        crumb="Overview", section=DATASETS, priority="0.9", freq="monthly",
        ld=lambda url: {
            "@type": "DataCatalog",
            "@id": url + "#catalog",
            "name": "Kestrel Datasets",
            "description": "Four corpora behind Kestrel's Linux detection "
                           "coverage, each kept separate and carrying its own "
                           "provenance.",
            "url": url,
            "publisher": {"@type": "Organization", "name": NAME,
                          "url": f"{SITE}/"},
            "dataset": [
                {"@type": "Dataset", "name": n, "url": f"{SITE}/{p}"}
                for n, p in (
                    ("ATT&CK Framework — Linux Surface", "datasets-attack.html"),
                    ("Linux Reference Index", "datasets-linux.html"),
                    ("Living off the Land — Abuse Functions and Baseline",
                     "datasets-lotl.html"),
                    ("eBPF Program Types and Capability", "datasets-ebpf.html"),
                )
            ],
        },
    ),
    "datasets-attack.html": dict(
        title="ATT&CK® Framework Dataset — The Linux Surface // Kestrel",
        desc="MITRE ATT&CK v19 reduced to its Linux surface: tactics, "
             "techniques, detection strategies, analytics and data components, "
             "each joined by one event key.",
        crumb="ATT&CK® Framework", section=DATASETS,
        priority="0.8", freq="monthly",
        ld=lambda url: dataset_ld(
            url, "ATT&CK Framework — Linux Surface",
            "MITRE ATT&CK v19 as a STIX bundle, reduced to the part observable "
            "on Linux and resolved from tactic through technique, "
            "sub-technique, detection strategy and analytic to the data "
            "components a sensor produces. A second corpus maps the same "
            "techniques to Linux-targeting campaigns.",
            ["MITRE ATT&CK", "Linux", "detection engineering", "analytics",
             "data components", "threat campaigns", "STIX"],
            "MITRE ATT&CK® © The MITRE Corporation",
        ),
    ),
    "datasets-linux.html": dict(
        title="Linux Reference Dataset — Syscalls, /proc, Symbols // Kestrel",
        desc="A cross-referenced index of the Linux system surface — "
             "syscalls, error codes, /proc, library symbols, programs — "
             "derived from its sources, never hand-written.",
        crumb="Linux Reference", section=DATASETS,
        priority="0.8", freq="monthly",
        ld=lambda url: dataset_ld(
            url, "Linux Reference Index",
            "A cross-referenced map of the Linux system surface, from syscalls "
            "and error codes through /proc, library symbols, programs and "
            "platform identities. Stratified into documented, observed and "
            "inferred layers, each record naming the method that produced it. "
            "Built to derive and validate features from, not to train on: it "
            "carries no labels and no folds.",
            ["Linux", "syscalls", "procfs", "ELF symbols", "man-pages",
             "kernel ABI", "reference dataset"],
            None,
        ),
    ),
    "datasets-lotl.html": dict(
        title="Living off the Land Dataset — GTFOBins and Tooling // Kestrel",
        desc="What a legitimate Linux binary can be made to do: GTFOBins "
             "abuse functions, the offensive tooling attackers bring, and "
             "the benign baseline both are judged on.",
        crumb="Living off the Land", section=DATASETS,
        priority="0.8", freq="monthly",
        ld=lambda url: dataset_ld(
            url, "Living off the Land — Abuse Functions and Baseline",
            "Three joined bodies of data on the abuse of legitimate binaries: "
            "the GTFOBins corpus of binaries and the functions each can be "
            "coerced into performing with the invocations kept whole, the "
            "offensive tooling attackers bring with them, and the benign "
            "baseline that says what those same binaries look like when "
            "nothing is wrong.",
            ["living off the land", "LOLBins", "GTFOBins", "Linux",
             "offensive tooling", "baseline", "detection engineering"],
            "GTFOBins © the GTFOBins authors",
        ),
    ),
    "datasets-ebpf.html": dict(
        title="eBPF Programs Dataset — Attach Points, Capability // Kestrel",
        desc="The honest bound on what a Linux detection can observe: eBPF "
             "program types, attach points, helpers, maps, kfuncs, kernel "
             "version floors and verifier scope.",
        crumb="eBPF Programs", section=DATASETS,
        priority="0.8", freq="monthly",
        ld=lambda url: dataset_ld(
            url, "eBPF Program Types and Capability",
            "The eBPF program types the Linux kernel exposes, the helpers, map "
            "types, kfuncs and syscall commands each may reach, the kernel "
            "version each appeared in and the verifier scope that applies. "
            "Attach points say where a probe would go for a given data "
            "component; the capability matrix says what that probe could do "
            "once loaded.",
            ["eBPF", "BPF", "Linux kernel", "attach points", "kernel helpers",
             "kfuncs", "observability"],
            "eBPF documentation © the eBPF-Docs Authors (BSD-2-Clause)",
        ),
    ),
}

# Pages kept out of the index: placeholder scaffolding with no search value.
NOINDEX = {"docs/index.html"}


def dataset_ld(url, name, description, keywords, attribution):
    """schema.org/Dataset node — the shape Google Dataset Search reads."""
    # creator/publisher are spelled out rather than referenced by @id: a
    # parser only sees one page at a time, so a reference to a node defined
    # on the home page resolves to nothing.
    org = {"@type": "Organization", "name": NAME, "url": f"{SITE}/"}
    node = {
        "@type": "Dataset",
        "@id": url + "#dataset",
        "name": name,
        "description": description,
        "url": url,
        "keywords": keywords,
        "inLanguage": "en",
        "isAccessibleForFree": True,
        "license": f"{SITE}/",
        "creator": org,
        "publisher": org,
        "includedInDataCatalog": {
            "@type": "DataCatalog",
            "name": "Kestrel Datasets",
            "url": f"{SITE}/dataset.html",
        },
    }
    if attribution:
        node["sourceOrganization"] = {"@type": "Organization",
                                      "name": attribution}
    return node


def page_url(f):
    return f"{SITE}/" if f == "index.html" else f"{SITE}/{f}"


def esc(s):
    """Attribute-safe text. The table holds plain text, so entities in the
    page title (&reg;, &amp;) are written here rather than carried through."""
    return html.escape(s, quote=True)


def build_jsonld(f, rec):
    url = page_url(f)
    graph = []

    if f == "index.html":
        graph.append({
            "@type": "Organization",
            "@id": f"{SITE}/#org",
            "name": NAME,
            "url": f"{SITE}/",
            "slogan": TAGLINE,
            "description": "Linux detection engineering: MITRE ATT&CK "
                           "coverage joined to eBPF telemetry.",
            "logo": {
                "@type": "ImageObject",
                "url": f"{SITE}/assets/img/kestrel-icon.jpg",
                "width": 144, "height": 216,
            },
        })
        graph.append({
            "@type": "WebSite",
            "@id": f"{SITE}/#website",
            "name": NAME,
            "alternateName": "Kestrel Signals",
            "url": f"{SITE}/",
            "description": rec["desc"],
            "inLanguage": "en",
            "publisher": {"@id": f"{SITE}/#org"},
        })

    graph.append({
        "@type": "WebPage",
        "@id": url + "#webpage",
        "url": url,
        "name": rec["title"],
        "description": rec["desc"],
        "isPartOf": {"@id": f"{SITE}/#website"},
        "inLanguage": "en",
        "primaryImageOfPage": {"@type": "ImageObject", "url": OG_IMAGE},
    })

    if rec["crumb"]:
        items = [{"@type": "ListItem", "position": 1, "name": "Home",
                  "item": f"{SITE}/"}]
        pos = 2
        if rec["section"]:
            label, href = rec["section"]
            crumb = {"@type": "ListItem", "position": pos, "name": label}
            # The References row is a nav toggle, not a page of its own, so it
            # appears in the trail without an item URL.
            if href:
                crumb["item"] = f"{SITE}/{href}"
            items.append(crumb)
            pos += 1
        items.append({"@type": "ListItem", "position": pos,
                      "name": rec["crumb"], "item": url})
        graph.append({
            "@type": "BreadcrumbList",
            "@id": url + "#breadcrumb",
            "itemListElement": items,
        })

    if rec["ld"]:
        graph.append(rec["ld"](url))

    return json.dumps({"@context": "https://schema.org", "@graph": graph},
                      indent=2, ensure_ascii=False)


def build_block(f, rec):
    url = page_url(f)
    t, d = esc(rec["title"]), esc(rec["desc"])
    lines = [
        SEO_START,
        f'<meta name="description" content="{d}">',
        f'<link rel="canonical" href="{url}">',
        '<meta name="robots" content="index, follow, max-snippet:-1, '
        'max-image-preview:large, max-video-preview:-1">',
        f'<meta name="theme-color" content="{THEME}">',
        f'<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{NAME}">',
        '<meta property="og:locale" content="en_US">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:title" content="{t}">',
        f'<meta property="og:description" content="{d}">',
        f'<meta property="og:image" content="{OG_IMAGE}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{esc(OG_ALT)}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{t}">',
        f'<meta name="twitter:description" content="{d}">',
        f'<meta name="twitter:image" content="{OG_IMAGE}">',
        f'<meta name="twitter:image:alt" content="{esc(OG_ALT)}">',
        '<script type="application/ld+json">',
        build_jsonld(f, rec),
        '</script>',
        SEO_END,
    ]
    return "\n".join(lines)


def apply_page(f, rec):
    """Replace the page's <title> and its generated head block. Returns the
    new text, or None when nothing changes."""
    h = open(f, encoding="utf-8").read()
    orig = h

    title_tag = f"<title>{html.escape(rec['title'], quote=False)}</title>"
    h, n = re.subn(r"<title>.*?</title>", lambda _: title_tag, h,
                   count=1, flags=re.S)
    if not n:
        raise SystemExit(f"seo: {f} has no <title>")

    block = build_block(f, rec)
    if SEO_START in h:
        h = re.sub(re.escape(SEO_START) + r".*?" + re.escape(SEO_END),
                   lambda _: block, h, count=1, flags=re.S)
    else:
        # Straight after <title>, before the stylesheet and script links.
        h = h.replace(title_tag, title_tag + "\n" + block, 1)

    return None if h == orig else h


def git_lastmod(f):
    """Last commit date for a page, falling back to its mtime for one that is
    not committed yet."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", f],
            capture_output=True, text=True, check=True).stdout.strip()
        if out:
            return out
    except (OSError, subprocess.CalledProcessError):
        pass
    import datetime
    return datetime.date.fromtimestamp(os.path.getmtime(f)).isoformat()


def build_sitemap():
    entries = []
    for f, rec in PAGES.items():
        entries.append(
            "  <url>\n"
            f"    <loc>{page_url(f)}</loc>\n"
            f"    <lastmod>{git_lastmod(f)}</lastmod>\n"
            f"    <changefreq>{rec['freq']}</changefreq>\n"
            f"    <priority>{rec['priority']}</priority>\n"
            "  </url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(entries)
            + "\n</urlset>\n")


def build_robots():
    return (
        "# https://www.robotstxt.org/robotstxt.html\n"
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        "# Generated delivery copies and raw data: the pages that present\n"
        "# them are what should rank, not the payloads themselves.\n"
        "Disallow: /assets/data/\n"
        "Disallow: /assets/journal/\n"
        "Disallow: /assets/vendor/\n"
        "Disallow: /docs/\n"
        "\n"
        f"Sitemap: {SITE}/sitemap.xml\n")


def write(path, text, check, stale):
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old == text:
        return
    stale.append(path)
    if not check:
        open(path, "w", encoding="utf-8").write(text)


def main():
    check = "--check" in sys.argv[1:]
    root = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                          capture_output=True, text=True, check=True).stdout.strip()
    os.chdir(root)

    stale = []

    # Every page on disk has to be in the table, or it ships with no metadata.
    on_disk = {f for f in glob.glob("*.html") if not f.startswith("_")}
    missing = on_disk - set(PAGES)
    if missing:
        raise SystemExit("seo: not in the page table: " + ", ".join(sorted(missing)))
    gone = set(PAGES) - on_disk
    if gone:
        raise SystemExit("seo: in the page table but not on disk: "
                         + ", ".join(sorted(gone)))

    for f, rec in PAGES.items():
        if len(rec["desc"]) > 160:
            print(f"  warn: {f} description is {len(rec['desc'])} chars "
                  "(search results truncate around 160)")
        if len(rec["title"]) > 65:
            print(f"  warn: {f} title is {len(rec['title'])} chars "
                  "(search results truncate around 60)")
        new = apply_page(f, rec)
        if new is not None:
            stale.append(f)
            if not check:
                open(f, "w", encoding="utf-8").write(new)

    for f in NOINDEX:
        if not os.path.exists(f):
            continue
        h = open(f, encoding="utf-8").read()
        if 'name="robots"' not in h:
            new = h.replace("</title>",
                            '</title>\n  <meta name="robots" content="noindex, follow">',
                            1)
            if new != h:
                stale.append(f)
                if not check:
                    open(f, "w", encoding="utf-8").write(new)

    write("sitemap.xml", build_sitemap(), check, stale)
    write("robots.txt", build_robots(), check, stale)

    # A page with no <h1> gives search engines no heading to read.
    for f in PAGES:
        if "<h1" not in open(f, encoding="utf-8").read():
            print(f"  warn: {f} has no <h1>")

    if check:
        if stale:
            print("seo: out of date: " + ", ".join(sorted(stale)))
            return 1
        print("seo: metadata, robots.txt and sitemap.xml are current")
        return 0

    print(f"  updated {len(stale)} file(s)" if stale else "  (already current)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
